---
title: "作业答案"
output: html_document
---

安装程序包，建议服务器改成清华大学

```r
#install.packages(c("repmis","plotrix","vioplot","fmsb","aplpack","DescTools","TeachingDemos","agricolae","pastecs","BSDA","car","psych","lm.beta","forecast","R.cache","R.methodsS3","R.oo","R.utils"))
```
Reading a Rdata file from github

```r
library(repmis)
```

```
## Warning: 程辑包'repmis'是用R版本3.6.2 来建造的
```

# 第一章
## 1.1下面是按收入五等划分的我国农村平均收入数据（单位：元）
### 1.1.1 在R中录入上表数据，并存为R格式

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch1/exercise1_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch1/exercise1_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 5b57dc17dc8bcd806f3932a52766e26097aab052
```

```
## [1] "exercise1_1"
```

```r
head(exercise1_1,10)
```

```
##         指标 X2008年 X2009年 X2010年 X2011年 X2012年
## 1   低收入户    1500    1549    1870    2001    2316
## 2 中等偏下户    2935    3110    3621    4256    4808
## 3 中等收入户    4203    4502    5222    6208    7041
## 4 中等偏上户    5929    6468    7441    8894   10142
## 5   高收入户   11290   12319   14050   16783   19009
```

### 1.1.2将上述数据框转换为矩阵

```r
aver_income=as.matrix(exercise1_1[,2:6])
aver_income
```

```
##      X2008年 X2009年 X2010年 X2011年 X2012年
## [1,]    1500    1549    1870    2001    2316
## [2,]    2935    3110    3621    4256    4808
## [3,]    4203    4502    5222    6208    7041
## [4,]    5929    6468    7441    8894   10142
## [5,]   11290   12319   14050   16783   19009
```

```r
rownames(aver_income)=exercise1_1[,1]
aver_income
```

```
##            X2008年 X2009年 X2010年 X2011年 X2012年
## 低收入户      1500    1549    1870    2001    2316
## 中等偏下户    2935    3110    3621    4256    4808
## 中等收入户    4203    4502    5222    6208    7041
## 中等偏上户    5929    6468    7441    8894   10142
## 高收入户     11290   12319   14050   16783   19009
```

```r
colnames(aver_income)=gsub("X","",colnames(aver_income))
aver_income
```

```
##            2008年 2009年 2010年 2011年 2012年
## 低收入户     1500   1549   1870   2001   2316
## 中等偏下户   2935   3110   3621   4256   4808
## 中等收入户   4203   4502   5222   6208   7041
## 中等偏上户   5929   6468   7441   8894  10142
## 高收入户    11290  12319  14050  16783  19009
```

## 1.2下表是2014年我国各地区的地区生产总值数据

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch1/exercise1_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch1/exercise1_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## c76281be6d868de9a6dd9bcdb37764b956937913
```

```
## [1] "exercise1_2"
```

```r
head(exercise1_2,10)
```

```
##            地区 地区生产总值
## 1        北京市     21330.83
## 2        天津市     15726.93
## 3        河北省     29421.15
## 4        山西省     12761.49
## 5  内蒙古自治区     17770.19
## 6        辽宁省     28626.58
## 7        吉林省     13803.14
## 8      黑龙江省     15039.38
## 9        上海市     23567.70
## 10       江苏省     65088.32
```
### 1.2.1按地区生产总值多少进行升序和降序排序

```r
gdp2014=exercise1_2
gdp2014_increasing=gdp2014[order(gdp2014$"地区生产总值"),]
gdp2014_decreasing=gdp2014[order(-gdp2014$"地区生产总值"),]
head(gdp2014_increasing,10)
```

```
##                地区 地区生产总值
## 26       西藏自治区       920.83
## 29           青海省      2303.32
## 30   宁夏回族自治区      2752.10
## 21           海南省      3500.72
## 28           甘肃省      6836.82
## 24           贵州省      9266.39
## 31 新疆维吾尔自治区      9273.46
## 4            山西省     12761.49
## 25           云南省     12814.59
## 7            吉林省     13803.14
```

```r
head(gdp2014_decreasing,10)
```

```
##      地区 地区生产总值
## 19 广东省     67809.85
## 10 江苏省     65088.32
## 15 山东省     59426.59
## 11 浙江省     40173.03
## 16 河南省     34938.24
## 3  河北省     29421.15
## 6  辽宁省     28626.58
## 23 四川省     28536.66
## 17 湖北省     27379.22
## 18 湖南省     27037.32
```
### 1.2.2将地区生产总值重新命名为GDP,并存为R数据格式

```r
library(repmis)
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch1/exercise1_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch1/exercise1_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## c76281be6d868de9a6dd9bcdb37764b956937913
```

```
## [1] "exercise1_2"
```

```r
exercise112=c(exercise1_2)
exercise112
```

```
## $地区
##  [1] 北京市           天津市           河北省           山西省          
##  [5] 内蒙古自治区     辽宁省           吉林省           黑龙江省        
##  [9] 上海市           江苏省           浙江省           安徽省          
## [13] 福建省           江西省           山东省           河南省          
## [17] 湖北省           湖南省           广东省           广西壮族自治区  
## [21] 海南省           重庆市           四川省           贵州省          
## [25] 云南省           西藏自治区       陕西省           甘肃省          
## [29] 青海省           宁夏回族自治区   新疆维吾尔自治区
## 31 Levels: 安徽省 北京市 福建省 甘肃省 广东省 广西壮族自治区 贵州省 ... 重庆市
## 
## $地区生产总值
##  [1] 21330.83 15726.93 29421.15 12761.49 17770.19 28626.58 13803.14 15039.38
##  [9] 23567.70 65088.32 40173.03 20848.75 24055.76 15714.63 59426.59 34938.24
## [17] 27379.22 27037.32 67809.85 15672.89  3500.72 14262.60 28536.66  9266.39
## [25] 12814.59   920.83 17689.94  6836.82  2303.32  2752.10  9273.46
```
### 1.2.3分别采用有放回抽样和无放回抽样两种方式各随机抽取6个地区作为样本

```r
sample(exercise1_2$地区,6,replace = FALSE)
```

```
## [1] 福建省 甘肃省 天津市 上海市 云南省 重庆市
## 31 Levels: 安徽省 北京市 福建省 甘肃省 广东省 广西壮族自治区 贵州省 ... 重庆市
```

```r
sample(exercise1_2$地区,6,replace = TRUE)
```

```
## [1] 内蒙古自治区     新疆维吾尔自治区 辽宁省           黑龙江省        
## [5] 江苏省           河北省          
## 31 Levels: 安徽省 北京市 福建省 甘肃省 广东省 广西壮族自治区 贵州省 ... 重庆市
```
### 1.2.4分别筛选出地区生产总值小于2万亿元和大于5万亿元的地区

```r
sample(exercise1_2$地区[exercise1_2$GDP<20000])
```

```
## factor(0)
## 31 Levels: 安徽省 北京市 福建省 甘肃省 广东省 广西壮族自治区 贵州省 ... 重庆市
```

```r
sample(exercise1_2$地区[exercise1_2$GDP>50000])
```

```
## factor(0)
## 31 Levels: 安徽省 北京市 福建省 甘肃省 广东省 广西壮族自治区 贵州省 ... 重庆市
```
## 1.3用R生产20个标准正态分布随机数，将其组织成4*5和5*4的矩阵

```r
rnorm(20)
```

```
##  [1] -1.13213180 -0.80369881 -0.82110719 -0.85141028 -0.04428808 -0.30165006
##  [7]  1.10738025 -0.95597493 -1.13048948 -0.37251629 -0.57747654  0.82087395
## [13] -1.66928755 -0.29843403 -1.18071365  1.06990886 -0.44219022 -2.22921104
## [19]  0.45791960 -1.53119329
```

```r
y<-rnorm(20)
matrix1_3=matrix(y,nrow=4,ncol=5)
matrix1_3
```

```
##            [,1]       [,2]       [,3]       [,4]       [,5]
## [1,] -0.3657678  0.6749359  1.0004671 -2.1655818 -1.8283504
## [2,] -2.0451886 -0.2908448 -0.6924494 -1.6754509  1.5672743
## [3,] -0.3321393  0.8785821  0.6587942  1.5289471  1.8194773
## [4,]  0.9513059  0.5485498 -1.4529829  0.5107236 -0.1043616
```

```r
matrix1_4=matrix(y,nrow=5,ncol=4)
matrix1_4
```

```
##            [,1]       [,2]       [,3]       [,4]
## [1,] -0.3657678 -0.2908448  0.6587942  0.5107236
## [2,] -2.0451886  0.8785821 -1.4529829 -1.8283504
## [3,] -0.3321393  0.5485498 -2.1655818  1.5672743
## [4,]  0.9513059  1.0004671 -1.6754509  1.8194773
## [5,]  0.6749359 -0.6924494  1.5289471 -0.1043616
```
# 第二章 数据的可视化
## 2.1 为了了解消费者对不同行业的满意度，随机调查120个消费者，得到如下数据

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## aade6e771a97e63752b28d79051ffd2f4211443d
```

```
## [1] "exercise2_1"
```

```r
head(exercise2_1,10)
```

```
##      行业 性别 满意度
## 1  金融业   女   满意
## 2  航空业   女   满意
## 3  电信业   男 不满意
## 4  金融业   女   满意
## 5  航空业   男 不满意
## 6  电信业   女   满意
## 7  金融业   女 不满意
## 8  金融业   男   满意
## 9  旅游业   女 不满意
## 10 金融业   男 不满意
```
### 2.1.1生成简单频数分布表、二维列联表和三维列联表

```r
summary(exercise2_1)
```

```
##      行业    性别       满意度  
##  电信业:38   男:58   不满意:75  
##  航空业:19   女:62   满意  :45  
##  金融业:26                      
##  旅游业:37
```

### 生成行业和性别的二维列联表

```r
table1=table(exercise2_1$"行业",exercise2_1$"性别")
addmargins(table1)
```

```
##         
##           男  女 Sum
##   电信业  17  21  38
##   航空业  10   9  19
##   金融业  14  12  26
##   旅游业  17  20  37
##   Sum     58  62 120
```

### 生成行业和满意度的二维列联表

```r
table2=table(exercise2_1$"行业",exercise2_1$"满意度")
addmargins(table2)
```

```
##         
##          不满意 满意 Sum
##   电信业     25   13  38
##   航空业     12    7  19
##   金融业     11   15  26
##   旅游业     27   10  37
##   Sum        75   45 120
```

### 生成性别和满意度的二维列联表

```r
table3=table(exercise2_1$"性别",exercise2_1$"满意度")
addmargins(table3)
```

```
##      
##       不满意 满意 Sum
##   男      36   22  58
##   女      39   23  62
##   Sum     75   45 120
```

### 生成三维列联表

```r
table4=ftable(exercise2_1)
table4
```

```
##             满意度 不满意 满意
## 行业   性别                   
## 电信业 男              11    6
##        女              14    7
## 航空业 男               7    3
##        女               5    4
## 金融业 男               7    7
##        女               4    8
## 旅游业 男              11    6
##        女              16    4
```

### 2.1.2分别绘制关于行业、性别和满意度的条形图

```r
load("c:/exercise/ch2/exercise2_1.RData")
count1<-table(exercise2_1$行业)
count2<-table(exercise2_1$性别)
count3<-table(exercise2_1$满意度)
par(mfrow=c(1,3),pin=c(1.2,1.2),cex=0.7,cex.main=0.8)
bar<-barplot(count1,xlab="频数",ylab="行业",horiz=TRUE,xlim=c(0,1.2*max(count1)),main="(a)水平条形图",col=2:5)
text(bar,count1,labels=count1,pos=4,adj=c(0,0.5))
bar<-barplot(count2,xlab="性别",ylab="频数",col=c("gray40","gray80"),ylim=c(0,1.2*max(count2)),main="(b)垂直条形图")
 text(bar,count2,labels=count2,pos=3,col=2)
 bar<-barplot(count3,xlab="满意度",ylab="频数",ylim=c(0,1.1*max(count3)),col=2:3,main="(c)垂直条形图")
text(bar,count3/2,labels=count3,pos=3,col=4)
```

<img src="112_files/figure-html/unnamed-chunk-17-1.png" width="672" />

### 绘制不同行业满意度人数的帕累托图

```r
count1=table(exercise2_1$"行业")
par(pin=c(3,2),cex=0.8)
x=sort(count1,decreasing=T)
bar<-barplot(x,xlab="行业",ylab="频数",col=rainbow(4),ylim=c(0,1.2*max(count1)))
text(bar,x,labels=x,pos=3,col=1)
y<-cumsum(x)/sum(x)
par(new=T)
plot(y,type="b",lwd=1.5,pch=15,axes=FALSE,xlab='',ylab='',main='')
axis(4)
mtext("累积频率",side=4,line=3,cex=.8)
mtext("累积分布曲线",line=-2.5,cex=.8,adj=0.75)
```

<img src="112_files/figure-html/unnamed-chunk-18-1.png" width="672" />

### 复式条形图---行业和满意度

```r
mytable1=table(exercise2_1$"满意度",exercise2_1$"行业")
par(pin=c(3,2),cex=0.6)
bar1<-barplot(mytable1,xlab="行业",ylab="频数",ylim=c(0,30),col=c("pink","lightblue"),legend=rownames(mytable1),args.legend=list(x=9),,beside=T)
text(bar1,mytable1,labels=mytable1,pos=3,col=1)
```

<img src="112_files/figure-html/unnamed-chunk-19-1.png" width="672" />

### 复式条形图---性别和满意度

```r
mytable2=table(exercise2_1$"满意度",exercise2_1$"性别")
mytable2
```

```
##         
##          男 女
##   不满意 36 39
##   满意   22 23
```

```r
par(mai=c(0.5,0.5,0.1,0.1),cex=0.6)
bar2=barplot(mytable2,xlab="性别",ylab="频数",ylim=c(0,45),col=c("lightblue","pink"),legend=rownames(mytable2),args.legend=list(x=4),beside=T)
text(bar2,mytable2,labels=mytable2,pos=3,col=2)
```

<img src="112_files/figure-html/unnamed-chunk-20-1.png" width="384" />

### 绘制马赛克图

```r
par(pin=c(2.5,2.5),cex=0.8)
mosaicplot(~性别+行业+满意度,data=exercise2_1,color=2:3,main="")
```

<img src="112_files/figure-html/unnamed-chunk-21-1.png" width="384" />

### 2.1.3绘制饼图和扇形图对各类别的百分比进行分析

```r
count1<-table(exercise2_1$行业)
name<-names(count1)
percent<-prop.table(count1)*100
label1<-paste(name," ",percent,"%",sep="")
par(pin=c(3,2),pin=c(3,2),cex=0.8)
pie(count1,labels=label1,init.angle=90,radius=1)
```

<img src="112_files/figure-html/unnamed-chunk-22-1.png" width="384" />

### 绘制扇形图

```r
name<-names(count1)
percent<-count1/sum(count1)*100
percent=round(percent,2)
labs<-paste(name," ",percent,"%",sep="")
library(plotrix)
fan.plot(mar=c(0.7,0.7,0.5,0.3),count1,labels=labs,ticks=10)
```

<img src="112_files/figure-html/unnamed-chunk-23-1.png" width="384" />

 分析：在调查的120个消费者中，其中31.67%的消费者对电信行业满意度做出评价，仅15.83%的消费者对航空业，满意度做出评价。电信行业受众广，被调查者在该四个行业中接触最多的也是电信行业，易做出评价，而航空业与大多数居民无直接关系，接触较少故较不容易做出评价。

## 2.2灯泡使用寿命测试（单位：小时）

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 54db476f273dacabf70d0f6317ef04c50800dcbc
```

```
## [1] "exercise2_2"
```

```r
head(exercise2_2,10)
```

```
##    灯泡寿命
## 1      3149
## 2      3075
## 3      3545
## 4      2963
## 5      3649
## 6      3344
## 7      3385
## 8      3289
## 9      3856
## 10     3081
```

### 2.2.1将数据分为10组，生成频数分布表

```r
vector2_2<-as.vector(exercise2_2$"灯泡寿命")
d=table(cut(vector2_2,breaks=150*(18:28),right=FALSE))
df=data.frame(d)
df
```

```
##                  Var1 Freq
## 1  [2.7e+03,2.85e+03)    1
## 2    [2.85e+03,3e+03)    4
## 3    [3e+03,3.15e+03)    8
## 4  [3.15e+03,3.3e+03)   10
## 5  [3.3e+03,3.45e+03)   12
## 6  [3.45e+03,3.6e+03)   22
## 7  [3.6e+03,3.75e+03)   14
## 8  [3.75e+03,3.9e+03)   17
## 9  [3.9e+03,4.05e+03)    9
## 10 [4.05e+03,4.2e+03)    3
```

```r
percent=df$Freq/sum(df$Freq)*100
cumsump=cumsum(percent)
mytable=data.frame(d,percent,cumsump)
mytable
```

```
##                  Var1 Freq percent cumsump
## 1  [2.7e+03,2.85e+03)    1       1       1
## 2    [2.85e+03,3e+03)    4       4       5
## 3    [3e+03,3.15e+03)    8       8      13
## 4  [3.15e+03,3.3e+03)   10      10      23
## 5  [3.3e+03,3.45e+03)   12      12      35
## 6  [3.45e+03,3.6e+03)   22      22      57
## 7  [3.6e+03,3.75e+03)   14      14      71
## 8  [3.75e+03,3.9e+03)   17      17      88
## 9  [3.9e+03,4.05e+03)    9       9      97
## 10 [4.05e+03,4.2e+03)    3       3     100
```

### 2.2.2绘制直方图

```r
load("C:/exercise/ch2/exercise2_2.RData")
d<-exercise2_2$灯泡寿命
par(cex=0.7,mai=c(0.6,0.6,0.2,0.1))
hist(d,ylim=c(0,30),labels=T,xlab="小时",ylab="频数",main="灯泡使用寿命直方图")
```

<img src="112_files/figure-html/unnamed-chunk-26-1.png" width="288" />

### 绘制茎叶图

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 54db476f273dacabf70d0f6317ef04c50800dcbc
```

```
## [1] "exercise2_2"
```

```r
stem(exercise2_2$灯泡寿命)
```

```
## 
##   The decimal point is 2 digit(s) to the right of the |
## 
##   26 | 0
##   28 | 968
##   30 | 0557882356799
##   32 | 7888990134569
##   34 | 11335667799112223344455559
##   36 | 033566600024445567788
##   38 | 22455566670055669
##   40 | 001017
```

分析：由茎叶图可直观看出，灯泡使用寿命最小值为2700小时，最大使用寿命为4169小时。其中，灯泡使用寿命集中在3500—3700小时之间。

## 2.3下面是我国10个城市2006年各月份的气温数据

### 2.3.1按城市绘制箱线图和小提琴图

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 9cce6345fcbddf5eb957bfcae527dac8872f99b1
```

```
## [1] "exercise2_3"
```

```r
par(mai=c(0.5,0.5,0.2,0.2))
boxplot(exercise2_3,col="pink",ylab="气温",xlab="城市",cex.lab=.8,cex.axis=.7,main="气温")
library(vioplot)
```

```
## 载入需要的程辑包：sm
```

```
## Package 'sm', version 2.2-5.6: type help(sm) for summary information
```

```
## 载入需要的程辑包：zoo
```

```
## 
## 载入程辑包：'zoo'
```

```
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
```

<img src="112_files/figure-html/unnamed-chunk-28-1.png" width="480" />

```r
x1=exercise2_3$"北京"
x2=exercise2_3$"沈阳"
x3=exercise2_3$"上海"
x4=exercise2_3$"南昌"
x5=exercise2_3$"郑州"
x6=exercise2_3$"武汉"
x7=exercise2_3$"广州"
x8=exercise2_3$"海口"
x9=exercise2_3$"重庆"
x10=exercise2_3$"昆明"
vioplot(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,col="lightblue",names=c("北京","沈阳","上海","南昌","郑州","武汉","广州","海口","重庆","昆明"),pin=c(2,1.5))
```

```
## [1] -12.7  32.4
```

<img src="112_files/figure-html/unnamed-chunk-28-2.png" width="480" />

### 2.3.2按城市绘制点图和核密度估计曲线

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_3_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_3_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## aa7e4ad9218ecd7ae88a85f4495f05a09a03065e
```

```
## [1] "exercise2_3_1"
```

```r
par(mai=c(.8,.8,.1,.1),cex=.8)
dotchart(exercise2_3_1$气温,groups=
exercise2_3_1$城市,xlab="气温",pch=12,col="brown")
```

<img src="112_files/figure-html/unnamed-chunk-29-1.png" width="384" />

### 2.3.3按城市绘制轮廓图和雷达图

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 9cce6345fcbddf5eb957bfcae527dac8872f99b1
```

```
## [1] "exercise2_3"
```

```r
par(mai=c(.7,.7,.1,.1),cex=.8)
matplot(t(exercise2_3[2:11]),type='b',lty=1:12,col=rainbow(12),lwd=2,xlab="城市",ylab ="气温",pch=1,xaxt="n")
axis(side=1,at=2:11,labels=c("北京","沈阳","上海","南昌","郑州","武汉","广州","海口","重庆","昆明"),cex.axis=0.7)
legend(x="topright",legend=exercise2_3[,1],lty=1:12,col=rainbow(12),text.width=2,cex=0.8)
```

<img src="112_files/figure-html/unnamed-chunk-30-1.png" width="384" />

### 绘制雷达图

```r
par(mai=c(0.5,0.5,0.5,0.5),cex=0.8)
library(fmsb)
radarchart(exercise2_3[,2:11],axistype=0,seg=4,maxmin=FALSE,vlabels=names(exercise2_3[,2:11]),pcol=rainbow(7),plwd=3)
legend(x="topleft",legend=c("北京","沈阳","上海","南昌","郑州","武汉","广州","海口","重庆","昆明"),col=1:10,lwd=1,text.width=0.5,cex=0.7)
```

<img src="112_files/figure-html/unnamed-chunk-31-1.png" width="384" />

### 2.3.4分别按月份和城市绘制星图和脸谱图

```r
matrix2_3=as.matrix(exercise2_3[,2:11])
rownames(matrix2_3)=exercise2_3[,1] 
stars(matrix2_3,key.loc=c(10,2,5),cex=0.8,main='不同月份的星图')
```

<img src="112_files/figure-html/unnamed-chunk-32-1.png" width="576" />

### 按月份绘制星图

```r
stars(t(matrix2_3),full=F,draw.segments=TRUE,key.loc=c(10,1.85,5),cex=0.8,main='不同城市的星图')
```

<img src="112_files/figure-html/unnamed-chunk-33-1.png" width="672" />

### 绘制脸谱图

```r
library(aplpack)
faces(matrix2_3,nrow.plot=3,ncol.plot=4,face.type=3,main='不同月份的脸谱图')
```

<img src="112_files/figure-html/unnamed-chunk-34-1.png" width="384" />

```
## effect of variables:
##  modified item       Var   
##  "height of face   " "北京"
##  "width of face    " "沈阳"
##  "structure of face" "上海"
##  "height of mouth  " "南昌"
##  "width of mouth   " "郑州"
##  "smiling          " "武汉"
##  "height of eyes   " "广州"
##  "width of eyes    " "海口"
##  "height of hair   " "重庆"
##  "width of hair   "  "昆明"
##  "style of hair   "  "北京"
##  "height of nose  "  "沈阳"
##  "width of nose   "  "上海"
##  "width of ear    "  "南昌"
##  "height of ear   "  "郑州"
```

```r
faces(t(matrix2_3),nrow.plot=2,ncol.plot=5,face.type=0,main='不同城市的脸谱图')
```

<img src="112_files/figure-html/unnamed-chunk-34-2.png" width="384" />

```
## effect of variables:
##  modified item       Var   
##  "height of face   " "1月" 
##  "width of face    " "2月" 
##  "structure of face" "3月" 
##  "height of mouth  " "4月" 
##  "width of mouth   " "5月" 
##  "smiling          " "6月" 
##  "height of eyes   " "7月" 
##  "width of eyes    " "8月" 
##  "height of hair   " "9月" 
##  "width of hair   "  "10月"
##  "style of hair   "  "11月"
##  "height of nose  "  "12月"
##  "width of nose   "  "1月" 
##  "width of ear    "  "2月" 
##  "height of ear   "  "3月"
```

## 2.4 下表是2011年我国31个地区的地区生产总值（按收入法计算）、全社会固定资产投资和最终消费支出数据（单位：亿元）

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_4.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_4.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 6adcb27197c97ad2d831fea085532b8db47b60ec
```

```
## [1] "exercise2_4"
```

```r
head(exercise2_4,10)
```

```
##      地区 地区生产总值 固定资产投资 最终消费支出
## 1   北 京      16251.9       5578.9       9488.2
## 2   天 津      11307.3       7067.7       4286.3
## 3   河 北      24515.8      16389.3       9633.8
## 4   山 西      11237.6       7073.1       4868.1
## 5  内蒙古      14359.9      10365.2       5526.6
## 6   辽 宁      22226.7      17726.3       8867.2
## 7   吉 林      10568.8       7441.7       4423.7
## 8  黑龙江      12582.0       7475.4       6586.7
## 9   上 海      19195.7       4962.1      10821.2
## 10  江 苏      49110.3      26692.6      20649.3
```

### 2.4.1绘制散点图和气泡图分析各变量之间的关系

### 散点图

```r
attach(exercise2_4)
par(mai=c(0.7,0.8,0.1,0.1),cex=0.6)
plot(固定资产投资,地区生产总值,xlab="",ylab="地区生产总值")
abline(lm(地区生产总值~固定资产投资,data=exercise2_4),lty=2)
points(最终消费支出,地区生产总值,pch=2,col="blue")
abline(lm(地区生产总值~最终消费支出,data=exercise2_4),col="blue",lty=3)
legend(0, 54000, c("对固定资产投资回归", "对最终消费支出回归"),col = c("black","blue"),lty = c(2, 3))
```

<img src="112_files/figure-html/unnamed-chunk-36-1.png" width="384" />

### 绘制气泡图

```r
par(mai=c(0.9,0.9,0.1,0.1))
r<- sqrt(地区生产总值/pi) 
symbols(固定资产投资,最终消费支出,circles=r,inches=0.3,fg="white",bg="lightblue", ylab="最终消费支出",xlab="固定资产投资",ylim=c(0,35000),xlim=c(0,30000))
text(固定资产投资,最终消费支出,rownames(exercise2_4),cex=0.6)
mtext("气泡大小 = 地区生产总值",line=-1,cex=.8,adj=0.1)
```

<img src="112_files/figure-html/unnamed-chunk-37-1.png" width="384" />

### 2.4.2绘制星图和脸谱图比较31个地区各项数据的相似性

### 按城市绘制星图

```r
matrix2_4=as.matrix(exercise2_4[,2:4])
rownames(matrix2_4)=exercise2_4[,1] 
stars(t(matrix2_4),full=F,draw.segments=TRUE,key.loc=c(10,1.85,5),cex=0.8,main='各指标星图')
```

<img src="112_files/figure-html/unnamed-chunk-38-1.png" width="288" />

### 脸谱图

```r
library(aplpack)
faces(t(matrix2_4),nrow.plot=1,ncol.plot=3,face.type=0,main='各指标的脸谱图',cex=0.9)
```

<img src="112_files/figure-html/unnamed-chunk-39-1.png" width="384" />

```
## effect of variables:
##  modified item       Var     
##  "height of face   " "北 京" 
##  "width of face    " "天 津" 
##  "structure of face" "河 北" 
##  "height of mouth  " "山 西" 
##  "width of mouth   " "内蒙古"
##  "smiling          " "辽 宁" 
##  "height of eyes   " "吉 林" 
##  "width of eyes    " "黑龙江"
##  "height of hair   " "上 海" 
##  "width of hair   "  "江 苏" 
##  "style of hair   "  "浙 江" 
##  "height of nose  "  "安 徽" 
##  "width of nose   "  "福 建" 
##  "width of ear    "  "江 西" 
##  "height of ear   "  "山 东"
```

## 2.5下表是2005年—2014年我国城镇居民和农村居民的CPI数据

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_5.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_5.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 35d26eaeef4a5d1454ffc37fbcad5b74b40f8833
```

```
## [1] "exercise2_5"
```

```r
exercise2_5
```

```
##    时间 城镇居民 农村居民
## 1  2005    101.6    102.2
## 2  2006    101.5    101.5
## 3  2007    104.5    105.4
## 4  2008    105.6    106.5
## 5  2009     99.1     99.7
## 6  2010    103.2    103.6
## 7  2011    105.3    105.8
## 8  2012    102.7    102.5
## 9  2013    102.6    102.8
## 10 2014    102.1    101.8
```

### 2.5.1绘制时间序列图，观察居民和农村居民消费价格指数的变化特征

```r
par(mai=c(0.7,0.7,0.1,0.1),cex=0.8,fg=2) 
plot(exercise2_5[,2],lwd=2,ylim=c(100,110),xlab="年份",ylab="居民消费水平",type="n")
grid(col="gray60")
points(exercise2_5[,2],type='o',lwd=2,ylim=c(100,110),xlab="年份",ylab="居民消费水平")
lines(exercise2_5[,3],type='b',lty=2,lwd=2,col="blue")
legend(x="topleft",legend=c("城镇居民","农村居民"),lty=1:2,col=c(1,3),cex=0.8)
```

<img src="112_files/figure-html/unnamed-chunk-41-1.png" width="384" />

  分析：2005年—2014年农村居民的消费价格指数整体上略高于城市，说明农村经济目前增速大于城市。但无论城市亦或农村CPI变化程度不大，说明物价相对稳定。

## 2.6 假定某地区不同收入阶层的人口数和不同阶层人口的年收入额如下表所示。绘制洛伦兹曲线分析收入分配的不平等程度。

### 绘制洛伦兹曲线分析收入分配的不平等程度

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_6.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch2/exercise2_6.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## c4107114056ddb92e9db50577b4e27e11d65581f
```

```
## [1] "exercise2_6"
```

```r
exercise2_6
```

```
##   不同阶层人口数的收入额 不同收入阶层的人口数
## 1                     10                   80
## 2                     15                   60
## 3                     30                   50
## 4                     50                   30
## 5                     60                   10
```

```r
library(DescTools)
```

```
## Registered S3 method overwritten by 'DescTools':
##   method       from   
##   plot.bagplot aplpack
```

```
## 
## 载入程辑包：'DescTools'
```

```
## The following object is masked from 'package:aplpack':
## 
##     plot.bagplot
```

```
## The following objects are masked from 'package:fmsb':
## 
##     CronbachAlpha, VIF
```

```r
Lc(exercise2_6$"不同阶层人口数的收入额",exercise2_6$"不同收入阶层的人口数")
```

```
## $p
## [1] 0.0000000 0.3478261 0.6086957 0.8260870 0.9565217 1.0000000
## 
## $L
## [1] 0.0000000 0.1509434 0.3207547 0.6037736 0.8867925 1.0000000
## 
## $L.general
## [1]    0  160  340  640  940 1060
## 
## $Gini
## [1] 0.3485211
## 
## $x
## [1] 10 15 30 50 60
## 
## $n
## [1] 80 60 50 30 10
## 
## attr(,"class")
## [1] "Lc"
```

```r
par(mai=c(0.7,0.7,0.4,0.1),cex=0.8)
plot(Lc(exercise2_6$"不同阶层人口数的收入额",exercise2_6$"不同收入阶层的人口数"),xlab="人数比例",ylab="收入比例",col=4,panel.first=grid(10,10,col="gray70"))
```

<img src="112_files/figure-html/unnamed-chunk-42-1.png" width="384" />

  分析：洛伦兹曲线弯曲程度较大，远离平均线，表示收入分配的不平等程度较大。

# 第三章 数据的描述统计量

## 3.1 50个消费者网购金额

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch3/exercise3_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch3/exercise3_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 8299c56f6a2d11b9db9400e4e709948807140ca1
```

```
## [1] "exercise3_1"
```

```r
head(exercise3_1,10)
```

```
##    网购金额
## 1      1004
## 2       921
## 3       928
## 4      1148
## 5      1416
## 6       602
## 7       990
## 8      1135
## 9       877
## 10     1380
```

### 3.1.1 计算平均数、标准差、极差和四分位数

```r
mean(exercise3_1$"网购金额")
```

```
## [1] 1032.64
```

```r
sd(exercise3_1$"网购金额")
```

```
## [1] 385.3728
```

```r
range=max(exercise3_1$"网购金额")-min(exercise3_1$"网购金额")
range
```

```
## [1] 1981
```

```r
IQR(exercise3_1$"网购金额",type=6)
```

```
## [1] 422.75
```

### 3.1.2计算10%，25%，50%，75%，90%的分位数

```r
quantile(exercise3_1$"网购金额",probs=c(0.1,0.25,0.5,0.75,0.90),type=6)
```

```
##     10%     25%     50%     75%     90% 
##  532.20  825.75  985.50 1248.50 1490.90
```

### 3.1.3计算标准分数检测离群点

### 计算标准分数并将结果保留四位小数

```r
a=round(scale(exercise3_1$"网购金额"),4)
```

### 方法筛选离群点

```r
subset(exercise3_1,网购金额>(3*sd(exercise3_1$"网购金额")+mean(exercise3_1$"网购金额"))|网购金额<((-3)*sd(exercise3_1$"网购金额")+mean(exercise3_1$"网购金额")))
```

```
##    网购金额
## 14     2270
```

### 3.1.4计算偏度系数和峰度系数，分析网购金额的分布特点

### 计算偏度系数

```r
library(agricolae)
```

```
## Registered S3 method overwritten by 'gdata':
##   method         from     
##   reorder.factor DescTools
```

```r
skewness(exercise3_1$"网购金额")
```

```
## [1] 0.6633022
```

```r
kurtosis(exercise3_1$"网购金额")
```

```
## [1] 1.220335
```
  分析：偏度系数为0.6633，属于中等偏斜分布，右偏分布。峰度系数为1.2203>0，为尖峰分布，数据相对集中。

## 3.2计算统计量及画箱线图

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch3/exercise3_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch3/exercise3_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 4a478e72c823836b141937aed3278c0949f57881
```

```
## [1] "exercise3_2"
```

```r
library(pastecs)
round(stat.desc(exercise3_2),4)
```

```
##                  方法A     方法B     方法C
## nbr.val        15.0000   15.0000   15.0000
## nbr.null        0.0000    0.0000    0.0000
## nbr.na          0.0000    0.0000    0.0000
## min           162.0000  125.0000  116.0000
## max           170.0000  132.0000  128.0000
## range           8.0000    7.0000   12.0000
## sum          2484.0000 1931.0000 1883.0000
## median        165.0000  129.0000  126.0000
## mean          165.6000  128.7333  125.5333
## SE.mean         0.5503    0.4522    0.7163
## CI.mean.0.95    1.1803    0.9698    1.5362
## var             4.5429    3.0667    7.6952
## std.dev         2.1314    1.7512    2.7740
## coef.var        0.0129    0.0136    0.0221
```

```r
par(mfrow=c(1,3),cex=0.6,mai=c(0.7,0.7,0.1,0.1))
boxplot(exercise3_2$"方法A",col="lightblue",xlab="方法A",ylab="产品数量",cex.lab=0.8,cex.axis=0.6)
boxplot(exercise3_2$"方法B",col="lightblue",xlab="方法B",ylab="产品数量",cex.lab=0.8,cex.axis=0.6)
boxplot(exercise3_2$"方法C",col="lightblue",xlab="方法C",ylab="产品数量",cex.lab=0.8,cex.axis=0.6)
```

<img src="112_files/figure-html/unnamed-chunk-49-1.png" width="384" />

## 3.3在大学生中随机抽取50名男生和50名女生，测得身高数据如下

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch3/exercise3_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch3/exercise3_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 9b0f4d747c7303e6d151348a5f9afb24c871dd73
```

```
## [1] "exercise3_3"
```

```r
head(exercise3_3,10)
```

```
##     男生  女生
## 1  182.1 175.4
## 2  183.3 162.7
## 3  176.6 174.6
## 4  177.3 164.8
## 5  174.3 157.0
## 6  178.9 157.3
## 7  177.5 164.3
## 8  179.5 167.6
## 9  168.3 167.8
## 10 173.3 168.7
```

### 绘制背靠背茎叶图，计算有关描述性统计量，比较男女生身高的特点和差异

### 背靠背茎叶图

```r
library(aplpack)
stem.leaf.backback(exercise3_3$"男生",exercise3_3$"女生")
```

```
## ____________________________________________
##   1 | 2: represents 12, leaf unit: 1 
##     exercise3_3$男生       exercise3_3$女生
## ____________________________________________
##                   | 15* |                   
##                   |   t |                   
##                   |   f |                   
##                   |   s |77             2   
##                   | 15. |8              3   
##                   | 16* |                   
##                   |   t |222333         9   
##                   |   f |44444555      17   
##    4          7766|   s |66677777777  (11)  
##    5             8| 16. |888888899     22   
##    7            10| 17* |01            13   
##    8             3|   t |2223          11   
##   18    5544444444|   f |44455          7   
##   (9)    777776666|   s |                   
##   23         98888| 17. |99             2   
##   18          1110| 18* |                   
##   14          3322|   t |                   
##   10             4|   f |                   
##    9            66|   s |                   
##    7         98888| 18. |                   
##    2             1| 19* |                   
##                   |   t |                   
##                   |   f |                   
##    1             6|   s |                   
##                   | 19. |                   
##                   | 20* |                   
## ____________________________________________
## n:              50       50            
## ____________________________________________
```

### 计算各统计量

```r
library(pastecs)
round(stat.desc(exercise3_3),4)
```

```
##                   男生      女生
## nbr.val        50.0000   50.0000
## nbr.null        0.0000    0.0000
## nbr.na          0.0000    0.0000
## min           166.5000  157.0000
## max           196.0000  179.2000
## range          29.5000   22.2000
## sum          8928.0000 8392.8000
## median        177.5000  167.7000
## mean          178.5600  167.8560
## SE.mean         0.9416    0.6981
## CI.mean.0.95    1.8922    1.4029
## var            44.3282   24.3670
## std.dev         6.6579    4.9363
## coef.var        0.0373    0.0294
```
 
  分析：由男生和女生的背靠背茎叶图可以看出，女生身高集中在160cm-175cm之间，而男生身高集中在170cm-190cm之间。分别计算男女生身高的统计量，男生平均身高为178.56，女生平均身高为167.856。比较而言，男生身高标准差为6.6579，大于女生身高标准差，所以男生之间身高差异较大。

# 第四章 随机变量的概率分布

## 4.1 消费者协会经过调查发现，某品牌冷气机重要缺陷的产品数出现的概率分布如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch4/exercise4_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch4/exercise4_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 5530a3c9c7ac457bf9e5a3e7678d4fba22fdd29c
```

```
## [1] "exercise4_1"
```

```r
exercise4_1
```

```
##     X     P
## 1   0 0.041
## 2   1 0.130
## 3   2 0.209
## 4   3 0.223
## 5   4 0.178
## 6   5 0.114
## 7   6 0.061
## 8   7 0.028
## 9   8 0.011
## 10  9 0.004
## 11 10 0.001
```
### 4.1.1有2~5台（包括2台与5台在内）冷气机出现重要缺陷的概率

```r
p1<-0.209	
p2<-0.223
p3<-0.178
p4<-0.114
p<-p1+p2+p3+p4
p
```

```
## [1] 0.724
```

### 4.1.2只有不到2台冷气机出现重要缺陷的概率

```r
p1<-0.041
p2<-0.130
pp<-p1+p2
pp
```

```
## [1] 0.171
```
### 4.1.3有超过5台冷气机出现重要缺陷的概率

```r
p1<-0.061
p2<-0.028
p3<-0.011
p4<-0.004
p5<-0.001
ppp<-p1+p2+p3+p4+p5
ppp
```

```
## [1] 0.105
```
## 4.2设X是参数为n=4和p=0.1的二项随机变量，求以下概率
### 4.2.1 P(X=2)

```r
dbinom(2,4,0.1) 
```

```
## [1] 0.0486
```
### 4.2.2 P(X≤1)

```r
pbinom(1,4,0.1) 
```

```
## [1] 0.9477
```
## 4.3 计算以下概率和分位点
### 4.3.1 X~N(500,20²);P(X≥510);P(400≤X≤450)

```r
1-pnorm(510,mean=500,sd=20)
```

```
## [1] 0.3085375
```

```r
pnorm(450,mean=500,sd=20)-pnorm(400,mean=500,sd=20)
```

```
## [1] 0.006209379
```
### 4.3.2 Z~N(0,1);P(0≤Z≤1.2);P(-0.48≤Z≤0);P(Z≥1.2)

```r
pnorm(1.2,mean=0,sd=1)-pnorm(0,mean=0,sd=1)
```

```
## [1] 0.3849303
```

```r
pnorm(0,mean=0,sd=1)-pnorm(-0.48,mean=0,sd=1)
```

```
## [1] 0.1843863
```

```r
1-pnorm(1.2,mean=0,sd=1)
```

```
## [1] 0.1150697
```
### 4.3.3标准正态分布累计频率为0.95时的反函数值z

```r
qnorm(0.475,mean=0,sd=1)
```

```
## [1] -0.06270678
```
## 4.4 计算以下概率和分位点：
### 4.4.1 X~t(df),df=15,t值小于-1.5的概率；df=20，t值大于2的概率；df=30,t分布右尾概率0.05时的t值

```r
pt(-1.5,df=15)
```

```
## [1] 0.07718333
```

```r
1-pt(2,df=20)
```

```
## [1] 0.02963277
```

```r
qt(0.95,df=30)
```

```
## [1] 1.697261
```

### 4.4.2 X~Chi-square(df),df=8,$\chi^2$值小于12的概率；df=20,$\chi^2$值大于18的概率;df=15.$\chi^2$分布右尾概率为0.025时的反函数值.

```r
pchisq(12,df=8)
```

```
## [1] 0.8487961
```

```r
1-pchisq(18,df=20)
```

```
## [1] 0.5874082
```

```r
qchisq(0.975,df=15)
```

```
## [1] 27.48839
```
## 4.5抽取不同的样本量模拟以下分布
### 4.5.1正态分布，来自正态总体的样本

```r
par(mai=c(0.75,0.75,0.1,0.1),cex=0.9)
curve(dnorm(x,0,sqrt(1/2)),from=-3,to=3,xlim=c(-4,4),ylab="f(x)",lty=1,col=2,lwd=3)
abline(h=0)
segments(0,0,0,0.56,col="blue",lty=2,lwd=1.5)
curve(dnorm(x,mean=0,sd=1),from=-4,to=4,add=TRUE,lty=2,lwd=3)
curve(dnorm(x,0,sqrt(2)),from=-4,to=4,add=TRUE,lty=3,col=4,lwd=3)
legend(x="topright",legend=c("N(0,0.5)","N(0,1)","N(0,2)"),inset=0.001,lty=1:3,col=c(2,"black",4))
```

<img src="112_files/figure-html/unnamed-chunk-64-1.png" width="384" />


### 4.5.2样本均值的分布，来自任意总体的样本

```r
par(mfrow=c(1,3),mai=c(0.7,0.7,0.4,0.2),cex=0.8)
x<-vector()
n=10
for(i in 1:1000){
  x<-append(x,mean(sample(100,n,replace=F)))
}
head(x,100)
```

```
##   [1] 55.9 38.6 53.7 58.6 50.6 59.2 54.6 45.5 53.0 57.8 36.7 52.8 49.5 48.8 55.8
##  [16] 62.0 43.5 58.6 46.9 40.8 67.1 59.2 41.1 53.9 51.8 55.0 67.5 53.8 64.2 36.0
##  [31] 70.7 53.5 49.7 60.0 41.6 54.1 45.1 40.9 51.4 50.6 67.7 46.3 48.7 56.6 61.0
##  [46] 52.6 48.8 46.7 54.2 46.7 53.3 44.2 43.1 39.0 43.3 45.8 48.8 46.6 41.6 54.6
##  [61] 31.5 48.7 77.0 51.5 56.4 55.3 68.9 47.8 50.1 37.6 40.6 39.7 45.2 65.9 52.6
##  [76] 49.6 46.9 51.5 55.8 62.9 63.4 43.4 46.0 41.3 43.3 41.4 47.7 40.5 57.5 67.2
##  [91] 53.3 53.2 57.2 53.0 66.9 54.3 36.6 57.0 50.2 50.3
```

```r
hist(x,prob=T,xlim=c(0,100),ylim=c(0,0.05),col="lightblue",xlab="样本均值",main="样本均值的分布",cex.main=.8)
lines(density(x),col="red",lwd=2)
x<-vector();m<-vector()
n=30
for(i in 1:1000){
  x<-append(x,mean(sample(100,n,replace=F)))
}
head(x,100)
```

```
##   [1] 51.90000 55.96667 48.96667 53.80000 44.53333 47.00000 56.53333 47.03333
##   [9] 52.50000 48.90000 54.70000 47.30000 53.70000 48.13333 46.93333 51.80000
##  [17] 52.56667 48.50000 55.86667 53.36667 43.20000 51.40000 56.26667 44.96667
##  [25] 51.23333 54.30000 45.03333 46.06667 49.73333 43.66667 42.26667 58.16667
##  [33] 50.00000 42.46667 54.13333 53.16667 49.86667 46.53333 58.60000 50.26667
##  [41] 50.30000 44.50000 60.73333 47.53333 47.80000 48.36667 47.00000 46.13333
##  [49] 50.76667 48.96667 58.50000 45.00000 50.06667 47.56667 48.66667 55.83333
##  [57] 50.83333 49.06667 50.33333 47.86667 52.10000 59.63333 55.06667 54.66667
##  [65] 46.33333 53.90000 54.66667 55.96667 39.30000 52.73333 42.23333 60.93333
##  [73] 55.10000 45.86667 51.16667 55.53333 53.16667 46.90000 54.30000 52.93333
##  [81] 48.36667 51.76667 54.80000 60.73333 45.33333 47.53333 48.90000 45.43333
##  [89] 49.36667 44.70000 54.90000 49.40000 55.56667 51.50000 56.46667 43.36667
##  [97] 55.06667 52.30000 45.76667 53.86667
```

```r
hist(x,prob=T,xlim=c(0,100),ylim=c(0,0.1),col="lightblue",xlab="样本均值",main="样本均值的分布",cex.main=.8)
lines(density(x),col="red",lwd=2)
x<-vector();m<-vector()
n=50
for(i in 1:1000){
  x<-append(x,mean(sample(100,n,replace=F)))
}
head(x,100)
```

```
##   [1] 51.04 54.04 49.08 50.22 45.26 49.22 47.48 51.32 49.84 54.76 51.44 42.76
##  [13] 50.38 48.62 53.62 45.20 49.82 51.86 48.20 52.90 52.34 53.32 46.36 52.74
##  [25] 48.94 52.02 45.66 53.62 50.20 50.54 52.16 50.86 48.04 49.50 51.00 50.16
##  [37] 52.38 51.72 52.44 44.86 42.70 52.88 51.60 53.30 51.90 54.98 52.74 46.00
##  [49] 52.54 49.78 44.52 48.82 49.58 45.08 46.64 49.10 52.84 53.52 48.86 53.08
##  [61] 46.66 46.98 51.26 47.64 54.00 49.96 52.46 50.64 52.78 53.86 55.02 48.84
##  [73] 47.76 48.82 46.64 51.82 49.90 54.82 51.96 51.86 48.38 52.18 48.32 51.18
##  [85] 44.16 50.48 51.80 50.84 53.78 51.46 46.46 50.74 46.16 55.42 49.82 49.32
##  [97] 47.26 52.42 45.96 49.84
```

```r
hist(x,prob=T,xlim=c(0,100),ylim=c(0,0.15),col="lightblue",xlab="样本均值",main="样本均值的分布",cex.main=.8)
lines(density(x),col="red",lwd=2)
```

<img src="112_files/figure-html/unnamed-chunk-65-1.png" width="480" />


### 4.5.3样本比例的分布，来自任意总体的样本

```r
par(mai=c(1.2,1.2,0.5,0.5))
p=rbinom(1000,1000,.2)/1000
head(p,100)
```

```
##   [1] 0.188 0.195 0.214 0.210 0.205 0.214 0.174 0.224 0.225 0.190 0.199 0.173
##  [13] 0.211 0.181 0.197 0.189 0.190 0.216 0.203 0.207 0.204 0.211 0.192 0.199
##  [25] 0.206 0.197 0.211 0.172 0.213 0.187 0.198 0.202 0.200 0.195 0.193 0.194
##  [37] 0.205 0.209 0.211 0.210 0.202 0.192 0.190 0.189 0.182 0.209 0.220 0.222
##  [49] 0.206 0.179 0.206 0.201 0.204 0.204 0.202 0.237 0.195 0.185 0.212 0.181
##  [61] 0.196 0.187 0.194 0.200 0.192 0.188 0.188 0.184 0.199 0.222 0.183 0.198
##  [73] 0.213 0.201 0.202 0.204 0.188 0.219 0.211 0.196 0.199 0.197 0.216 0.215
##  [85] 0.211 0.218 0.210 0.202 0.221 0.208 0.211 0.199 0.204 0.201 0.220 0.201
##  [97] 0.211 0.203 0.189 0.194
```

```r
hist(p,prob=T,xlim=c(0.1,0.3),ylim=c(0,34),col="lightblue",xlab="样本比例",main="模拟样本比例的分布",cex.main=.8)
lines(density(p),col="red",lwd=2)
```

<img src="112_files/figure-html/unnamed-chunk-66-1.png" width="480" />

### 4.5.4样本方差的分布，来自正态总体的样本

```r
v<-vector()
n=30
for(i in 1:1000){
  v<-append(v,var(rnorm(n)))
}
hist(v,prob=T,xlim=c(0,2),ylim=c(0,1.8),col="lightblue",xlab="样本方差",main="模拟样本方差的分布",cex.main=.8)
lines(density(v),col="red",lwd=2)
```

<img src="112_files/figure-html/unnamed-chunk-67-1.png" width="480" />


# 第5章 参数估计
## 5.1某快餐店想要估计每位顾客午餐的平均花费金额,在为期3周的时间里选取49名顾客组成了一个简单随机样本,得到样本均值为120元，标准差为15元，求总体均值μ的95％的置信区间。

```r
xbar=120
s=15
n=49
q=qnorm(0.975)
LCI=xbar-q*s/sqrt(n)
UCI=xbar+q*s/sqrt(n)
data.frame(LCI,UCI)
```

```
##        LCI      UCI
## 1 115.8001 124.1999
```
## 5.2 利用下面的信息，构建总体均值μ的置信区间
### 5.2.1总体服从正态分布。已知标准差\sigma=500，n=15，样本均值=8900。置信水平为95%

```r
xbar=8900
sigma=500
n=15
q=qnorm(0.975)
LCI=xbar-q*sigma/sqrt(n)
UCI=xbar+q*sigma/sqrt(n)
data.frame(LCI,UCI)
```

```
##       LCI     UCI
## 1 8646.97 9153.03
```


### 5.2.2总体不服从正态分布.已知\sigma=500，n=35，样本均值=8900。置信水平为95%.

```r
xbar=8900
sigma=500
n=35
q=qnorm(0.975)
LCI=xbar-q*sigma/sqrt(n)
UCI=xbar+q*sigma/sqrt(n)
data.frame(LCI,UCI)
```

```
##        LCI      UCI
## 1 8734.353 9065.647
```


### 5.2.3总体不服从正态分布。已知\sigma未知，n=35，样本均值=8900，s=510。置信水平为90%

```r
xbar=8900
s=510
n=35
q<-qnorm(0.95)
LCI=xbar-q*s/sqrt(n)
UCI=xbar+q*s/sqrt(n)
data.frame(LCI,UCI)
```

```
##        LCI      UCI
## 1 8758.204 9041.796
```
### 5.2.4总体不服从正态分布。已知\sigma未知，n=100，样本均值=8900，s=510。置信水平为95%

```r
xbar=8900
s=500
n=100
q=qnorm(0.975)
LCI=xbar-q*s/sqrt(n)
UCI=xbar+q*s/sqrt(n)
data.frame(LCI,UCI)
```

```
##        LCI      UCI
## 1 8802.002 8997.998
```

## 5.3 某大学为了了解学生每天上网的时间，在全校学生中随机抽取36人，调查他们每天的上网时间，得到的数据如下（单位：小时）：求该校大学生平均上网时间的置信区间，置信水平分别为90%，95%和99%。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch5/exercise5_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch5/exercise5_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 34bfb7e3fc3b900182b6114a7c73ded818d74425
```

```
## [1] "exercise5_3"
```

```r
head(exercise5_3,10)
```

```
##    上网时间
## 1       3.3
## 2       4.4
## 3       2.1
## 4       4.7
## 5       3.1
## 6       2.0
## 7       1.9
## 8       1.4
## 9       6.2
## 10      5.4
```


```r
library(BSDA)
```

```
## 载入需要的程辑包：lattice
```

```
## 
## 载入程辑包：'BSDA'
```

```
## The following object is masked from 'package:datasets':
## 
##     Orange
```

```r
z.test(exercise5_3$"上网时间",mu=0,sigma.x=sd(exercise5_3$"上网时间"),conf.level=0.90)
```

```
## 
## 	One-sample z-Test
## 
## data:  exercise5_3$上网时间
## z = 12.365, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 90 percent confidence interval:
##  2.875476 3.757857
## sample estimates:
## mean of x 
##  3.316667
```

```r
z.test(exercise5_3$"上网时间",mu=0,sigma.x=sd(exercise5_3$"上网时间"),conf.level=0.95)
```

```
## 
## 	One-sample z-Test
## 
## data:  exercise5_3$上网时间
## z = 12.365, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  2.790956 3.842377
## sample estimates:
## mean of x 
##  3.316667
```

```r
z.test(exercise5_3$"上网时间",mu=0,sigma.x=sd(exercise5_3$"上网时间"),conf.level=0.99)
```

```
## 
## 	One-sample z-Test
## 
## data:  exercise5_3$上网时间
## z = 12.365, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 99 percent confidence interval:
##  2.625766 4.007567
## sample estimates:
## mean of x 
##  3.316667
```

## 5.4 某居民小区共有居民500户，小区管理者准备采取一项新的供水设施，想了解居民是否赞成。采取重复抽样方法随机抽取了50户，其中有32户赞成，18户反对。估计总体中赞成采用新设施的户数比例的置信区间，置信水平为95％。

```r
n<-50
x<-32
p<-x/n
q<-qnorm(0.975)
LCI<-p-q*sqrt(p*(1-p)/n)
UCI<-p+q*sqrt(p*(1-p)/n)
data.frame(LCI,UCI)
```

```
##         LCI       UCI
## 1 0.5069532 0.7730468
```
## 5.5 为比较哪种排队方式使顾客等待的时间更短，银行各随机抽取10名顾客,他们在办理业务时所等待的时间(单位:分钟)如下:

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch5/exercise5_5.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch5/exercise5_5.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 3fbef3019ddd76dba516c6c6e3bdeab656cfc210
```

```
## [1] "exercise5_5"
```

```r
exercise5_5
```

```
##    方式1 方式2
## 1    6.5   4.2
## 2    6.6   5.4
## 3    6.7   5.8
## 4    6.8   6.2
## 5    7.1   6.7
## 6    7.3   7.7
## 7    7.4   7.7
## 8    7.7   8.5
## 9    7.7   9.3
## 10   7.7  10.0
```
### 5.5.1构建第一种排队方式等待时间均值的95%的置信区间

```r
library(BSDA)
z.test(exercise5_5$方式1,mu=0,sigma.x=sd(exercise5_5$方式1),conf.level=0.95)
```

```
## 
## 	One-sample z-Test
## 
## data:  exercise5_5$方式1
## z = 47.433, p-value < 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  6.854557 7.445443
## sample estimates:
## mean of x 
##      7.15
```


### 5.5.2构建第二种排队方式等待时间方差的95%的置信区间

```r
library(TeachingDemos)
```

```
## 
## 载入程辑包：'TeachingDemos'
```

```
## The following object is masked from 'package:BSDA':
## 
##     z.test
```

```
## The following objects are masked from 'package:aplpack':
## 
##     faces, slider
```

```r
sigma.test(exercise5_5$"方式2",conf.level=0.95)$conf.int
```

```
## [1]  1.569961 11.059516
## attr(,"conf.level")
## [1] 0.95
```


### 5.5.3构建两种方式排队时间均值之差的95%的置信区间

### 5.5.3.1方差相等

```r
t.test(x=exercise5_5$方式1,y=exercise5_5$方式2,var.equal=TRUE)$conf.int
```

```
## [1] -1.250985  1.250985
## attr(,"conf.level")
## [1] 0.95
```
### 5.5.3.2方差不相等

```r
t.test(x=exercise5_5$方式1,y=exercise5_5$方式2,var.equal=F)$conf.int
```

```
## [1] -1.322758  1.322758
## attr(,"conf.level")
## [1] 0.95
```
## 5.6根据已有数据构建两个正太分布总体

### 5.6.1计算$μ_1$-$μ_2$的95%的置信区间

```r
x<-rnorm(14,53.2,96.8)
y<-rnorm(7,43.4,102.0)
t.test(x,y,var.equal=TRUE,conf.level=0.95)$conf.int
```

```
## [1] -182.746401    5.476331
## attr(,"conf.level")
## [1] 0.95
```


### 5.6.2计算$μ_1$-$μ_2$的99%的置信区间

```r
x<-rnorm(14,53.2,96.8)
y<-rnorm(7,43.4,102.0)
t.test(x,y,var.equal=TRUE,conf.level=0.99)$conf.int
```

```
## [1] -155.7499  150.0063
## attr(,"conf.level")
## [1] 0.99
```
## 5.7 一家人才测评机构对随机抽取的10名小企业的经理人用两种方法进行的信心测试，得到的自信心测试分数如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch5/exercise5_7.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch5/exercise5_7.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## a022cf6795ce61d38dc003e9b489dabed68fd04d
```

```
## [1] "exercise5_7"
```

```r
exercise5_7
```

```
##    人员编号 方法1 方法2
## 1         1    78    71
## 2         2    63    44
## 3         3    72    61
## 4         4    89    84
## 5         5    91    74
## 6         6    49    51
## 7         7    68    55
## 8         8    76    60
## 9         9    85    77
## 10       10    55    39
```


 构建两种方法平均自信心得分之差$μ_d$=$μ_1$-$μ_2$的95%的置信区间

```r
t.test(exercise5_7$方法1,exercise5_7$方法2,paired=TRUE)$conf.int
```

```
## [1]  6.327308 15.672692
## attr(,"conf.level")
## [1] 0.95
```

## 5.8 从两个总体中各抽取一个$n_1$=$n_2$=250的独立随机样本，来自总体1的样本比例为$p_1$=40%，来自总体2的样本比例为$p_2$=30%
### 5.8.1构造$π_1$-$π_2$=90%的置信区间

```r
n1<-250
n2<-250
p1<-0.4
p2<-0.3
q<-qnorm(0.95)
LCI<-p1-p2-q*sqrt(p1*(1-p1)/n1+p2*(1-p2)/n2)
UCI<-p1-p2+q*sqrt(p1*(1-p1)/n1+p2*(1-p2)/n2)
data.frame(LCI,UCI) 
```

```
##          LCI       UCI
## 1 0.03021477 0.1697852
```


### 5.8.2构造$π_1$-$π_2$=95%的置信区间

```r
n1<-250
n2<-250
p1<-0.4
p2<-0.3
q<-qnorm(0.975)
LCI<-p1-p2-q*sqrt(p1*(1-p1)/n1+p2*(1-p2)/n2)
UCI<-p1-p2+q*sqrt(p1*(1-p1)/n1+p2*(1-p2)/n2)
data.frame(LCI,UCI)
```

```
##          LCI       UCI
## 1 0.01684577 0.1831542
```
## 5.9 生产工序的方差是工序质量的一个重要度量。当方差较大时，需要对工序进行改进以减小方差。下面是两部机器生产的袋茶重量(单位：g)的数据：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch5/exercise5_9.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch5/exercise5_9.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## be9c5040c57e258395eaeae3db7974c6b951194b
```

```
## [1] "exercise5_9"
```

```r
head(exercise5_9,10)
```

```
##    机器1 机器2
## 1   3.45  3.22
## 2   3.20  3.38
## 3   3.22  3.30
## 4   3.50  3.30
## 5   2.95  3.34
## 6   3.16  3.28
## 7   3.20  3.30
## 8   3.22  3.28
## 9   2.98  3.19
## 10  3.75  3.20
```


 构造两个总体方差比$σ_1$²/$σ_2$²的95%的置信区间

```r
var.test(exercise5_9$机器1,exercise5_9$机器2,alternative="two.sided")$conf.int
```

```
## [1]  4.051926 24.610112
## attr(,"conf.level")
## [1] 0.95
```
# 第6章 假设检验

## 6.1 一种机床加工的零件尺寸绝对平均误差为1.35mm，生产厂家准备采用一种新的机床以进一步降低误差，为检测新机床加工的零件平均误差与旧机床相比是否有显著降低，从新机床生产的零件中随机抽取50个进行检验。50个零件尺寸的绝对误差数据（单位：mm）如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 292371b236a4d1a345a60df0170600eb1155c11f
```

```
## [1] "exercise6_1"
```

```r
head(exercise6_1,10)
```

```
##    零件误差
## 1      1.26
## 2      1.13
## 3      0.98
## 4      1.12
## 5      1.23
## 6      0.99
## 7      1.98
## 8      1.11
## 9      1.70
## 10     1.17
```

### 6.1.1绘制Q-Q图，检验零件尺寸的绝对误差是否服从正态分布

```r
par(cex=0.8,mai=c(0.7,0.7,0.2,0.1))
qqnorm(exercise6_1$"零件误差",xlab="期望正态值",ylab="观测值",datax=TRUE,main="正态Q-Q图")
qqline(exercise6_1$"零件误差",datax=TRUE,col="red")
```

<img src="112_files/figure-html/unnamed-chunk-90-1.png" width="288" />

  分析：根据Q-Q图可直观看出，有较多观测点远离直线，故其不服从正态分布。
  
### 6.1.2检验新机床加工的零件尺寸的平均误差与旧机床相比是否有显著降低（α=0.01）

```r
library(BSDA)
ks.test(exercise6_1$零件误差,"pnorm", mean(exercise6_1$零件误差), sd(exercise6_1$零件误差))
```

```
## Warning in ks.test(exercise6_1$零件误差, "pnorm", mean(exercise6_1$零件误差), :
## ties should not be present for the Kolmogorov-Smirnov test
```

```
## 
## 	One-sample Kolmogorov-Smirnov test
## 
## data:  exercise6_1$零件误差
## D = 0.19126, p-value = 0.05157
## alternative hypothesis: two-sided
```

  分析：P值=0.004579＜α=0.01，所以拒绝原假设，认为绝对误差有显著降低。
  
## 6.2安装于一种联合收割机的金属板的平均重量为25千克。对某企业生产的20块金属板进行测量。得到的重量数据如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 29f7b4e033753cbb14a3eea288eaff76df4b4462
```

```
## [1] "exercise6_2"
```

```r
head(exercise6_2,10)
```

```
##    重量
## 1  22.6
## 2  27.0
## 3  26.2
## 4  25.8
## 5  22.2
## 6  26.6
## 7  25.3
## 8  30.4
## 9  23.2
## 10 28.1
```

### 6.2.1采用Shapiro-Wilk检验和K-S检验两种方法，检验该企业生产的金属板的重量是否服从正态分布（α=0.05）

### Shapiro-Wilk检验

```r
shapiro.test(exercise6_2$重量)              
```

```
## 
## 	Shapiro-Wilk normality test
## 
## data:  exercise6_2$重量
## W = 0.97064, p-value = 0.7684
```
  
  分析：H₀：金属板的重量服从正态分布。H₁：金属板的重量不服从正态分布，经Shapiro-Wilk检验可得，W=0.97064,p值=0.7684，p>0.05,所以不能拒绝原假设，认为金属板的重量服从正态分布。

### K-S检验

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 29f7b4e033753cbb14a3eea288eaff76df4b4462
```

```
## [1] "exercise6_2"
```

```r
ks.test(exercise6_2$重量,"pnorm", mean(exercise6_2$重量), sd(exercise6_2$重量))
```

```
## 
## 	One-sample Kolmogorov-Smirnov test
## 
## data:  exercise6_2$重量
## D = 0.10808, p-value = 0.9539
## alternative hypothesis: two-sided
```

  分析：经K-S检验可得，D=0.10808，p值=0.9539，p>0.05,所以接受原假设，认为金属板的重量服从正态分布。

### 6.2.2假定全属板的重量服从正态分布，检验该企业生产的金属板是否符合要求（α=0.05）

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 29f7b4e033753cbb14a3eea288eaff76df4b4462
```

```
## [1] "exercise6_2"
```

```r
t.test(exercise6_2$重量,mu = 25)
```

```
## 
## 	One Sample t-test
## 
## data:  exercise6_2$重量
## t = 1.0399, df = 19, p-value = 0.3114
## alternative hypothesis: true mean is not equal to 25
## 95 percent confidence interval:
##  24.48352 26.53648
## sample estimates:
## mean of x 
##     25.51
```

  分析:H₀:金属板的重量平均数μ＝25。H₁：金属板的重量平均数μ≠25,经t检验，得到mean of x=25.51,t=-5.627,df=19，p值=0.3114，p>0.05,拒绝原假设，有证据显示该企业生产的金属板不符合要求。

### 6.2.3计算效应量，分析差异程度。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 29f7b4e033753cbb14a3eea288eaff76df4b4462
```

```
## [1] "exercise6_2"
```

```r
sd(exercise6_2$重量)
```

```
## [1] 2.193267
```

分析：得到样本标准差s=2.193267，效应量d=|mean of x-x|/s=0.23252983，结果表示：样本金属板的平均重量与标准重量相差0.23252983，因为0.20≤d<0.50,为小的效应值。

## 6.3下表是样本中每个人都分别在看过该产品的新的电视广告之前与之后打分

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## cc3242ddd8d71d18bba490a86074c1a24b3e4334
```

```
## [1] "exercise6_3"
```

```r
exercise6_3
```

```
##   看后 看前
## 1    6    5
## 2    6    4
## 3    7    7
## 4    4    3
## 5    3    5
## 6    9    8
## 7    7    5
## 8    6    6
```

### 两个总体均值之差的假设检验

```r
t.test(exercise6_3$看后 , exercise6_3$看前,paired = TRUE,alternative = "greater")
```

```
## 
## 	Paired t-test
## 
## data:  exercise6_3$看后 and exercise6_3$看前
## t = 1.3572, df = 7, p-value = 0.1084
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  -0.2474397        Inf
## sample estimates:
## mean of the differences 
##                   0.625
```


  结论：在该项检验中，p值=0.1084>0.05,所以不能拒绝原假设，即认为“看后”平均得分小于或等于“看前”平均得分。

## 6.4下表是两种方法对员工培训的效果得到的测试分数结果的数据

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_4.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_4.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## d3edb4234758cc2b2a638c0f0925556efd170782
```

```
## [1] "exercise6_4"
```

```r
head(exercise6_4,10)
```

```
##    方法1 方法2
## 1     56    59
## 2     47    52
## 3     42    53
## 4     50    54
## 5     47    58
## 6     51    57
## 7     52    56
## 8     53    55
## 9     42    64
## 10    44    60
```

### 6.4.1假定方差相等（α=0.05）

```r
t.test(exercise6_4$方法1,exercise6_4$方法2,var.equal = TRUE)
```

```
## 
## 	Two Sample t-test
## 
## data:  exercise6_4$方法1 and exercise6_4$方法2
## t = -5.8927, df = 28, p-value = 2.444e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12.128568  -5.871432
## sample estimates:
## mean of x mean of y 
##  47.73333  56.73333
```

  分析：由配对样本t检验，H₀:两种方法的培训效果没有显著差异。H₁:两种方法的培训效果有显著差异。p-value = 2.444e-06<0.05,拒绝原假设，所以认为两种方法的培训效果有显著差异。

### 6.4.2假定方差不相等

```r
t.test(exercise6_4$方法1,exercise6_4$方法2,var.equal = FALSE)
```

```
## 
## 	Welch Two Sample t-test
## 
## data:  exercise6_4$方法1 and exercise6_4$方法2
## t = -5.8927, df = 27.639, p-value = 2.568e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12.130411  -5.869589
## sample estimates:
## mean of x mean of y 
##  47.73333  56.73333
```

  结论：由配对样本t检验，H₀:两种方法的培训效果没有显著差异。H₁:两种方法的培训效果有显著差异。p-value = 2.568e-06<0.05,拒绝原假设，所以认为两种方法的培训效果有显著差异
  
### 6.4.3计算效应量，分析差异程度

```r
library(lsr)
cohensD(exercise6_4$方法1,exercise6_4$方法2)
```

```
## [1] 2.151704
```

  结论：效应量:d值=2.151704，表示方法1的均值（𝜇~1~）与方法2的均值（𝜇~2~）相差2.151704个标准差，效应量较大。

## 6.5生产商随机抽取550人作为样本，其中115人早餐喝牛奶，验证该城市的人早产饮用牛奶的比例是够高于17%。检验该生产商的说法是否属实（α=0.05）

```r
n=550
p <- 115/550
pi0=0.17
z <- (p-pi0)/sqrt(pi0*(1-pi0)/n)
p_value <-1-pnorm(z)
data.frame(z,p_value)
```

```
##          z     p_value
## 1 2.440583 0.007331785
```

  结论:H₀: P<=0.17，H₁:P>0.17。检验得p=0.007<0.05，拒绝原假设，认为生产商的说法属实。

## 6.6随机抽取100女经理中有24人认为自己成功，95男经理中39人认为自己成功，检验男女认为自己成功比例是否有显著差异。

```r
n1=100
n2=95
p1=0.24
p2=0.41
p=(p1*n1+p2*n2)/(n1+n2)
z=(p1-p2)/sqrt(p*(1-p)*(1/n1+1/n2))
p_value=pnorm(z)
p_value1=2*p_value
data.frame(z, p_value1)
```

```
##           z   p_value1
## 1 -2.537821 0.01115451
```

  结论：H₀:男女经理认为自己成功的人数无显著差异，H₁:男女经理认为自己成功的人数有显著差异。p<0.05,拒绝原假设，即认为男女经理认为自己成功的人数有显著差异。

## 6.7土壤相同40块地，各20块用新旧两种肥料得到的产量表

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_7.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_7.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## be658e0187bd89768d8a64a87dded58214ae4d32
```

```
## [1] "exercise6_7"
```

```r
head(exercise6_7,10)
```

```
##    旧肥料 新肥料
## 1     109    105
## 2      98    113
## 3     103    106
## 4      97    110
## 5     101    109
## 6      98    111
## 7      88    117
## 8     105    111
## 9      97    110
## 10     94    111
```
### 6.7.1新肥料平均产量是否显著高于旧肥料，方差相等前提下。

```r
t.test(exercise6_7$新肥料,exercise6_7$旧肥料,var.equal=TRUE,alternative="greater")
```

```
## 
## 	Two Sample t-test
## 
## data:  exercise6_7$新肥料 and exercise6_7$旧肥料
## t = 5.4271, df = 38, p-value = 1.737e-06
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  6.341979      Inf
## sample estimates:
## mean of x mean of y 
##     109.9     100.7
```

  结论：H₀:使用新肥料的产量均值≤使用旧肥料产量均值，H₁:使用新肥料的产量的均值>使用旧肥料产量均值。p=1.737e-06<0.05，拒绝原假设，统计意义上认为新肥料产量明高于于旧肥料产量，所以应该使用新肥料。


### 6.7.2两种肥料产量方差是否有显著差异

```r
var.test(exercise6_7[,1],exercise6_7[,2])
```

```
## 
## 	F test to compare two variances
## 
## data:  exercise6_7[, 1] and exercise6_7[, 2]
## F = 0.72294, num df = 19, denom df = 19, p-value = 0.4862
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.2861488 1.8264749
## sample estimates:
## ratio of variances 
##           0.722941
```

  结论：H₀:两种肥料产量的方差无显著差异，H₁两种肥料产量的方差有显著差异。根据检验p=0.4862>0.05，不能拒绝原假设，认为两种肥料产量的方差无显著性差异。
  
### 6.7.3计算效应量，分析差异程度。

```r
library(lsr)
 cohensD(exercise6_7$旧肥料,exercise6_7$新肥料)
```

```
## [1] 1.716202
```

  结论：新肥料与旧肥料的效应量为1.716202，即新肥料与旧肥料均值相差 1.716202个标准差，效应量较大。
  
## 6.8生产工序中的方差是工序质量的一个重要指标。通常较大的方差就意味着要通过寻找减小工序方差的途径来改进工作。某杂志上刊载了两台机器生产的袋茶重量的数据（单位：克）如下：检验这两部机器生产的袋茶重量的方差是否存在显著差异（ɑ=0.05）。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_8.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_8.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 15e967dabfde7042094193ec1921b66da9f2c4e0
```

```
## [1] "exercise6_8"
```

```r
var.test(exercise6_8[,1],exercise6_8[,2],alternative="two.sided")
```

```
## 
## 	F test to compare two variances
## 
## data:  exercise6_8[, 1] and exercise6_8[, 2]
## F = 9.0711, num df = 23, denom df = 23, p-value = 1.477e-06
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##   3.924078 20.969026
## sample estimates:
## ratio of variances 
##           9.071058
```

  结论：由两个总体的方差检验，H₀:两机器生产的袋茶重量的的方差无显著差异.H₁：两机器生产的袋茶重量的的方差有显著差异。p值=1.477e-06<0.05.拒绝原假设，即认为两机器生产的袋茶重量的的方差有显著差异。

## 6.9为了解一种节能灯的使用寿命，随机抽取了10只灯泡，测得其使用寿命（单位：小时）如下：采用Wilcoxon符号秩检验检验该种节能灯使用寿命的中位数是否等于6000小时（ɑ=0.05）。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_9.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_9.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 8168bbbfe46e1fa2d8e001e73769f8a8d1e7001f
```

```
## [1] "exercise6_9"
```

```r
 wilcox.test(exercise6_9$寿命,m = 6000)
```

```
## 
## 	Wilcoxon signed rank test
## 
## data:  exercise6_9$寿命
## V = 41, p-value = 0.1934
## alternative hypothesis: true location is not equal to 6000
```

  结论：由Wilcoxon符号秩检验，H₀:使用寿命的中位数等于6000。H₁:使用寿命的中位数不等于6000。p值=0.1934>0.05，因此不能拒绝原假设，即认为使用寿命的中位数的等于6000.
  
## 6.10某种品牌的彩电在两个城市销售，在A城市和B城市各有8个商场销售。下表是各商场一年的销售量（单位：台）。采用Mann-Whitney检验分析两个城市的销售量是否有显著差异（ɑ=0.05）。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_10.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_10.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## a852bb38730dc5e03af5c8837dbe3d6d78976795
```

```
## [1] "exercise6_10"
```

```r
 attach(exercise6_10)
 wilcox.test(A城市,B城市)
```

```
## Warning in wilcox.test.default(A城市, B城市): cannot compute exact p-value with
## ties
```

```
## 
## 	Wilcoxon rank sum test with continuity correction
## 
## data:  A城市 and B城市
## W = 26.5, p-value = 0.5992
## alternative hypothesis: true location shift is not equal to 0
```

  结论：由Mann-Whitney检验，H₀:两个城市的销售量无显著差异。H₁：两个城市的销售量由显著差异。p值=0.5992>0.05，不能拒绝原假设，即认为两个城市的销售量无显著差异

## 6.11为分析股票的每股盈利状况，在某证券市场上随机抽取10只股票，得到上年度和本年度的每股盈利（单位：元）数据如下表所示，采用Wilcoxon符号秩检验分析：本年度与上年度相比，每股盈利是否有显著提高（ɑ=0.05）。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_11.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch6/exercise6_11.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 29089136ff0fd0f68e359df111817da26a87cc61
```

```
## [1] "exercise6_11"
```

```r
 attach(exercise6_11)
 wilcox.test(上年度,本年度,paired=TRUE)
```

```
## Warning in wilcox.test.default(上年度, 本年度, paired = TRUE): cannot compute
## exact p-value with ties
```

```
## 
## 	Wilcoxon signed rank test with continuity correction
## 
## data:  上年度 and 本年度
## V = 10, p-value = 0.08293
## alternative hypothesis: true location shift is not equal to 0
```

  结论：由两个配对样本的Wilcoxon符号秩检验，H₀:本年度与上年度相比，每股盈利无显著提高；H₁:本年度与上年度相比，每股盈利有显著提高。由SPSS的Wilcoxon符号秩检验，α=0.05，得到p值=0.08293。p/2=0.041465<0.05,拒绝原假设，即认为本年度与上年度相比，每股盈利有显著提高。

# 第7章 类别变量分析
## 7.1一家食品生产企业想了解过去一年中各个月份的销售量是否符合均匀分布，以便更好地安排生产。企业的市场销售部门收集的过去一年中每个月的销售量数据如下：
 检验各个月份的销售量是否符合均匀分布（α=0.05）
 H₀：各个月份的销售量符合均匀分布 
 H₁：各个月份的销售量不符合均匀分布

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch7/exercise7_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch7/exercise7_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## d510502cfaea987732d6d62192d200033b3d5250
```

```
## [1] "exercise7_1"
```

```r
exercise7_1
```

```
##    月份 销售量
## 1   1月   1660
## 2   2月   1600
## 3   3月   1560
## 4   4月   1490
## 5   5月   1380
## 6   6月   1620
## 7   7月   1580
## 8   8月   1680
## 9   9月   1550
## 10 10月   1370
## 11 11月   1410
## 12 12月   1610
```

```r
chisq.test(exercise7_1$销售量)
```

```
## 
## 	Chi-squared test for given probabilities
## 
## data:  exercise7_1$销售量
## X-squared = 80.924, df = 11, p-value = 9.778e-13
```


 p-value=9.778e-13<0.05,则拒绝原假设，统计意义上认为各个月份的销售量不符合均匀分布。

## 7.2 为研究大学生的逃课情况，一个研究小组做了一次调查，得到男女生逃课情况的汇总表如下：检验是否逃课与学生性别是否独立（α=0.05）
 H₀：是否逃课与学生性别独立 
 H₁：是否逃课与学生性别不独立

```r
x<-c(34,28,38,50) 
M<-matrix(x,nr=2,nc=2,byrow=TRUE,dimnames=list(c("男","女"),c("逃过课","没逃过课")))
chisq.test(M)
```

```
## 
## 	Pearson's Chi-squared test with Yates' continuity correction
## 
## data:  M
## X-squared = 1.5407, df = 1, p-value = 0.2145
```
 p-value=0.2145＞0.05,故不能拒绝原假设，即不能认为是否逃课与学生性别不独立。

## 7.3为研究上市公司对其股价波动的关注程度，一家研究机构对在主板、中小板、创业板上市的190家公司进行了调查，检验上市公司的类型与对股价波动的关注程度是否独立。

```r
x<-c(50,70,30,15,20,5) 
M<-matrix(x,nr=3,nc=2,byrow=TRUE,dimnames=list(c("主板企业","中小板企业","创业板企业"),c("关注","不关注")))
M
```

```
##            关注 不关注
## 主板企业     50     70
## 中小板企业   30     15
## 创业板企业   20      5
```

```r
chisq.test(M)
```

```
## 
## 	Pearson's Chi-squared test
## 
## data:  M
## X-squared = 16.854, df = 2, p-value = 0.0002189
```
 H₀：上市公司的类型与对股价波动的关注程度独立

 H₁：上市公司的类型与对股价波动的关注程度不独立

 由检验结果可知p-value = 0.0002189<0.05，拒绝H₀，认为上市公司的类型与对股价波动的关注程度不独立。

## 7.4一家汽车企业的销售部门对北部地区、中部地区和南部地区的400个消费者做了抽烟调查，检验地区与汽车价格是否独立。

```r
y<-c(20,40,40,50,50,60,30,20,20,40,10,20) 
N<-matrix(y,nr=4,nc=3,byrow=TRUE,dimnames=list(c("10万元以下","10万~20万元","20~30万元","30万元以上"),c("北部地区","南部地区","中部地区")))
N
```

```
##             北部地区 南部地区 中部地区
## 10万元以下        20       40       40
## 10万~20万元       50       50       60
## 20~30万元         30       20       20
## 30万元以上        40       10       20
```

```r
chisq.test(N)
```

```
## 
## 	Pearson's Chi-squared test
## 
## data:  N
## X-squared = 29.991, df = 6, p-value = 3.946e-05
```
 H₀：地区与汽车价格独立

 H₁：地区与汽车价格不独立

 由检验结果可知p-value = 3.946e-05<0.05，拒绝H₀，认为地区与汽车价格不独立。

## 7.5计算习题7.3中上市公司的类型对股价波动的关注程度两个变量之间的phi系数、Crammer's系数和列联系数，并分析其相关程度。

```r
library(vcd)
```

```
## 载入需要的程辑包：grid
```

```
## 
## 载入程辑包：'vcd'
```

```
## The following object is masked from 'package:BSDA':
## 
##     Trucks
```

```
## The following object is masked from 'package:fmsb':
## 
##     oddsratio
```

```r
x=c(50,70,30,15,20,5)
M=matrix(x,nrow=3,ncol=2,byrow=T,dimnames=list(c("主板企业","中小板企业","创业板企业"),c("关注","不关注")))
M
```

```
##            关注 不关注
## 主板企业     50     70
## 中小板企业   30     15
## 创业板企业   20      5
```

```r
assocstats(M)
```

```
##                     X^2 df   P(> X^2)
## Likelihood Ratio 17.557  2 0.00015404
## Pearson          16.854  2 0.00021891
## 
## Phi-Coefficient   : NA 
## Contingency Coeff.: 0.285 
## Cramer's V        : 0.298
```
 分析：phi系数只用于2*2列联表，故没有结果。Crammer's系数V=0.298，列联系数C=0.298，表明上市公司的类型与对股价波动的关注程度有一定的相关性。

## 7.6计算习题7.4中地区与汽车价格两个变量之间的phi系数、Crammer's系数和列联系数，并分析其相关程度。

```r
library(vcd)
y<-c(20,40,40,50,50,60,30,20,20,40,10,20) 
N<-matrix(y,nr=4,nc=3,byrow=TRUE,dimnames=list(c("10万元以下","10万~20万元","20~30万元","30万元以上"),c("北部地区","南部地区","中部地区")))
N
```

```
##             北部地区 南部地区 中部地区
## 10万元以下        20       40       40
## 10万~20万元       50       50       60
## 20~30万元         30       20       20
## 30万元以上        40       10       20
```

```r
assocstats(N)
```

```
##                     X^2 df   P(> X^2)
## Likelihood Ratio 30.683  6 2.9134e-05
## Pearson          29.991  6 3.9455e-05
## 
## Phi-Coefficient   : NA 
## Contingency Coeff.: 0.264 
## Cramer's V        : 0.194
```

 分析：phi系数只用于2*2列联表，故没有结果。Crammer's系数V=0.194，列联系数C=0.264，表明上市公司的类型与对股价波动的关注程度有一定的相关性。


# 第8章 方差分析

## 8.1一家牛奶公司有4台机器装填牛奶,每桶的容量为4L

### 8.1.1检验机器对装填量是否有显著性影响。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## a9f1d3d24164ac8da65ba809c32e3eca59fa8618
```

```
## [1] "exercise8_1"
```

```r
head(exercise8_1,10)
```

```
##     机器 填装量
## 1  机器1   4.05
## 2  机器1   4.01
## 3  机器1   4.02
## 4  机器1   4.04
## 5  机器1   4.00
## 6  机器1   4.03
## 7  机器2   3.99
## 8  机器2   4.02
## 9  机器2   4.01
## 10 机器2   3.99
```

```r
attach(exercise8_1)
model_1w<-aov(填装量~机器)
summary(model_1w)
```

```
##             Df   Sum Sq   Mean Sq F value Pr(>F)  
## 机器         3 0.005846 0.0019486   4.576 0.0135 *
## Residuals   20 0.008517 0.0004258                 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

```r
model_1w$coefficients
```

```
## (Intercept)   机器机器2   机器机器3   机器机器4 
##  4.02500000 -0.01500000 -0.04333333 -0.01666667
```

 H₀:机器对装填量的影响不显著
 H₁:机器对装填量的影响显著
 由分析结果可知，p=0.0135>0.01，不拒绝H₀，即不能认为机器对装填量的影响显著。

### 8.1.2分析效应量。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## a9f1d3d24164ac8da65ba809c32e3eca59fa8618
```

```
## [1] "exercise8_1"
```

```r
attach(exercise8_1)
```

```
## The following objects are masked from exercise8_1 (pos = 3):
## 
##     机器, 填装量
```

```r
library(DescTools)
model_1w<-aov(填装量~机器)
EtaSq(model_1w,anova=T)
```

```
##              eta.sq eta.sq.part          SS df           MS        F          p
## 机器      0.4070206   0.4070206 0.005845833  3 0.0019486111 4.575995 0.01348501
## Residuals 0.5929794          NA 0.008516667 20 0.0004258333       NA         NA
```

 由效应量结果$\eta^2$=0.4070206可知，组间差异较大。

### 8.1.3分别采用LSD方法和HSD方法比较哪些机器的装填量之间存在显著差异。

```r
library(DescTools)
PostHocTest(model_1w,method="lsd")
```

```
## 
##   Posthoc multiple comparisons of means : Fisher LSD 
##     95% family-wise confidence level
## 
## $机器
##                     diff       lwr.ci       upr.ci   pval    
## 机器2-机器1 -0.015000000 -0.039852260  0.009852260 0.2225    
## 机器3-机器1 -0.043333333 -0.068185594 -0.018481073 0.0016 ** 
## 机器4-机器1 -0.016666667 -0.041518927  0.008185594 0.1772    
## 机器3-机器2 -0.028333333 -0.053185594 -0.003481073 0.0275 *  
## 机器4-机器2 -0.001666667 -0.026518927  0.023185594 0.8901    
## 机器4-机器3  0.026666667  0.001814406  0.051518927 0.0367 *  
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

 H₀：$n_i$=$n_j$
 H₁：$n_i$≠$n_j$
 由LSD分析结果可知：                                 
 机器2-机器1的p-value=0.2225>0.05,不拒绝H₀，即不能认为机器2与机器1之间有显著差异；        

 机器3-机器1的p-value=0.0016<0.05,拒绝H₀,认为机器3与机器1之间有显著差异；                  

 机器4-机器1的p-value=0.1772>0.05,不拒绝H₀，即不能认为机器4与机器1之间有显著差异；           
 机器3-机器2的p-value=0.0275<0.05,拒绝H₀,认为机器3与机器2之间有显著差异；    

 机器4-机器2的p-value=0.8901>0.05,不拒绝H₀，即不能认为机器4与机器2之间有显著差异；           
 机器4-机器3的p-value=0.0367<0.05,拒绝H₀,认为机器4与机器3之间有显著差异；


```r
PostHocTest(model_1w,method="hsd")
```

```
## 
##   Posthoc multiple comparisons of means : Tukey HSD 
##     95% family-wise confidence level
## 
## $机器
##                     diff       lwr.ci       upr.ci   pval    
## 机器2-机器1 -0.015000000 -0.048346648  0.018346648 0.5982    
## 机器3-机器1 -0.043333333 -0.076679982 -0.009986685 0.0082 ** 
## 机器4-机器1 -0.016666667 -0.050013315  0.016679982 0.5144    
## 机器3-机器2 -0.028333333 -0.061679982  0.005013315 0.1140    
## 机器4-机器2 -0.001666667 -0.035013315  0.031679982 0.9990    
## 机器4-机器3  0.026666667 -0.006679982  0.060013315 0.1471    
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

 H₀:$n_i$=$n_j$
 H₁:$n_i$≠$n_j$

 由HSD分析结果可知：

 机器2-机器1的p-value=0.5982>0.05,不拒绝H₀，即不能认为机器2与机器1之间有显著差异；

 机器3-机器1的p-value=0.0082<0.05,拒绝H₀,认为机器3与机器1之间有显著差异；   

 机器4-机器1的p-value=0.5144>0.05,不拒绝H₀，即不能认为机器4与机器1之间有显著差异；           
 机器3-机器2的p-value=0.1140>0.05,不拒绝H₀，即不能认为机器3与机器2之间有显著差异；           
 机器4-机器2的p-value=0.9990>0.05,不拒绝H₀，即不能认为机器4与机器2之间有显著差异；           
 机器4-机器3的p-value=0.1471>0.05,不拒绝H₀，即不能认为机器4与机器3之间有显著差异；


### 8.1.4检验装填量是否满足正态性和方差齐性。
### shapiro正态性检验

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## a9f1d3d24164ac8da65ba809c32e3eca59fa8618
```

```
## [1] "exercise8_1"
```

```r
attach(exercise8_1)
```

```
## The following objects are masked from exercise8_1 (pos = 3):
## 
##     机器, 填装量
```

```
## The following objects are masked from exercise8_1 (pos = 4):
## 
##     机器, 填装量
```

```r
shapiro.test(填装量)
```

```
## 
## 	Shapiro-Wilk normality test
## 
## data:  填装量
## W = 0.97509, p-value = 0.7912
```

 H₀：填装量服从正态分布
 H₁：填装量不服从正态分布
 由shapiro正态性检验可知，p-value = 0.7912>0.05,不拒绝H₀,可以认为填装量服从正态分布。


### Batrlett-检验

```r
bartlett.test(填装量~机器,data=exercise8_1)
```

```
## 
## 	Bartlett test of homogeneity of variances
## 
## data:  填装量 by 机器
## Bartlett's K-squared = 1.3927, df = 3, p-value = 0.7073
```

 H₀:各个总体方差相同
 H₁:所有总体方差中至少两个方差不同
 由Batrlett-方差齐性检验可知，p-value = 0.7073>0.05，不拒绝H₀，可以认为各个总体方差相同。

## 8.2一家管理咨询公司为不同的客户举办人力资源管理讲座。每次讲座的内容基本上是一样的，但讲座的听课者，有时是高级管理者，有时是中级管理者，有时是低级管理者。该咨询公司认为，不同层次的管理者对讲座的满意度是不同的，对听完讲座后随机抽取的不同层次管理者的满意度评分如下（评分标准从1——10，10代表非常满意）：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 68bc558dc6ec0a3c83d6f56d7f7603637d4120f8
```

```
## [1] "exercise8_2"
```

```r
exercise8_2
```

```
##        管理者 评分
## 1  高层管理者    7
## 2  高层管理者    7
## 3  高层管理者    8
## 4  高层管理者    7
## 5  高层管理者    9
## 6  高层管理者    8
## 7  中层管理者    8
## 8  中层管理者    9
## 9  中层管理者    8
## 10 中层管理者   10
## 11 中层管理者    9
## 12 中层管理者   10
## 13 低层管理者    5
## 14 低层管理者    6
## 15 低层管理者    5
## 16 低层管理者    7
## 17 低层管理者    4
## 18 低层管理者    8
```
### 8.2.1检验管理者的水平不同是否会导致评分的显著差异（α=0.05），并分析效应量。
 H₀：管理者的水平不同不会导致评分的显著差异
 H₁：管理者的水平不同会导致评分的显著差异

```r
attach(exercise8_2)
model_1w<-aov(评分~管理者)
summary(model_1w)
```

```
##             Df Sum Sq Mean Sq F value   Pr(>F)    
## 管理者       2  30.33  15.167   12.52 0.000633 ***
## Residuals   15  18.17   1.211                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

 p-value = 0.000633<0.05,则拒绝H₀，认为管理者的水平不同会导致评分的显著差异。

```r
library(DescTools)
attach(exercise8_2)
```

```
## The following objects are masked from exercise8_2 (pos = 3):
## 
##     管理者, 评分
```

```r
model_1w<-aov(评分~管理者)
EtaSq(model_1w,anova=T)
```

```
##              eta.sq eta.sq.part       SS df        MS        F            p
## 管理者    0.6254296   0.6254296 30.33333  2 15.166667 12.52294 0.0006331423
## Residuals 0.3745704          NA 18.16667 15  1.211111       NA           NA
```
 效应量= 0.6254296，则表明组间差异较大

### 8.2.2分别采用LSD方法和HSD方法比较管理者之间评分的差异

```r
library(agricolae)
model_1w<-aov(评分~管理者,data=exercise8_2)
LSD<-LSD.test(model_1w,"管理者");LSD
```

```
## $statistics
##    MSerror Df Mean      CV t.value      LSD
##   1.211111 15  7.5 14.6734 2.13145 1.354274
## 
## $parameters
##         test p.ajusted name.t ntr alpha
##   Fisher-LSD      none 管理者   3  0.05
## 
## $means
##                评分       std r      LCL      UCL Min Max  Q25 Q50  Q75
## 低层管理者 5.833333 1.4719601 6 4.875717 6.790949   4   8 5.00 5.5 6.75
## 高层管理者 7.666667 0.8164966 6 6.709051 8.624283   7   9 7.00 7.5 8.00
## 中层管理者 9.000000 0.8944272 6 8.042384 9.957616   8  10 8.25 9.0 9.75
## 
## $comparison
## NULL
## 
## $groups
##                评分 groups
## 中层管理者 9.000000      a
## 高层管理者 7.666667      a
## 低层管理者 5.833333      b
## 
## attr(,"class")
## [1] "group"
```
 结果显示如下：
 中层管理者 9.000000      a
 高层管理者 7.666667      a
 低层管理者 5.833333      b
 认为中层管理者和高层管理者之间差异不显著，低层管理者和中层管理者、低层管理者和高层管理者之间差异显著。

```r
library(agricolae)
HSD<-HSD.test(model_1w,"管理者");HSD
```

```
## $statistics
##    MSerror Df Mean      CV      MSD
##   1.211111 15  7.5 14.6734 1.650372
## 
## $parameters
##    test name.t ntr StudentizedRange alpha
##   Tukey 管理者   3         3.673378  0.05
## 
## $means
##                评分       std r Min Max  Q25 Q50  Q75
## 低层管理者 5.833333 1.4719601 6   4   8 5.00 5.5 6.75
## 高层管理者 7.666667 0.8164966 6   7   9 7.00 7.5 8.00
## 中层管理者 9.000000 0.8944272 6   8  10 8.25 9.0 9.75
## 
## $comparison
## NULL
## 
## $groups
##                评分 groups
## 中层管理者 9.000000      a
## 高层管理者 7.666667      a
## 低层管理者 5.833333      b
## 
## attr(,"class")
## [1] "group"
```
 分析：认为中层管理者和高层管理者之间差异不显著，低层管理者和中层管理者、低层管理者和高层管理者之间差异显著。

### 8.2.3检验满意度评分是否满足正态性和方差齐性。
### 正态性：
 H₀：总体满足正态分布
 H₁：总体不满足正态分布

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 68bc558dc6ec0a3c83d6f56d7f7603637d4120f8
```

```
## [1] "exercise8_2"
```

```r
attach(exercise8_2)
```

```
## The following objects are masked from exercise8_2 (pos = 3):
## 
##     管理者, 评分
```

```
## The following objects are masked from exercise8_2 (pos = 4):
## 
##     管理者, 评分
```

```r
shapiro.test(评分)
```

```
## 
## 	Shapiro-Wilk normality test
## 
## data:  评分
## W = 0.94141, p-value = 0.3063
```
 p-value = 0.3063>0.05,则不能拒绝原假设，认为总体满足正态分布。
### 方差齐性
 H₀：$\sigma_1^2$=$\sigma_2^2$=⋯=$\sigma_I^2$
 H₁：$\sigma_1^2$、$\sigma_2^2$、⋯、$\sigma_I^2$至少两个方差不同

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 68bc558dc6ec0a3c83d6f56d7f7603637d4120f8
```

```
## [1] "exercise8_2"
```

```r
library(car)
```

```
## 载入需要的程辑包：carData
```

```
## 
## 载入程辑包：'carData'
```

```
## The following objects are masked from 'package:BSDA':
## 
##     Vocab, Wool
```

```
## 
## 载入程辑包：'car'
```

```
## The following object is masked from 'package:DescTools':
## 
##     Recode
```

```r
leveneTest(评分~管理者,exercise8_2)
```

```
## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(>F)
## group  2  1.3636 0.2857
##       15
```
 p-value =0.2857>0.05，则不拒绝H₀，认为满意度评分满足方差齐性


### 8.2.4假定不同层次管理者的满意度评分不满足方差分析的假定。采用Kruskal-Wallis检验进行分析。
 H₀:所有总体都相同
 H₁:并非所有总体都相同

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 68bc558dc6ec0a3c83d6f56d7f7603637d4120f8
```

```
## [1] "exercise8_2"
```

```r
attach(exercise8_2)
```

```
## The following objects are masked from exercise8_2 (pos = 5):
## 
##     管理者, 评分
```

```
## The following objects are masked from exercise8_2 (pos = 6):
## 
##     管理者, 评分
```

```
## The following objects are masked from exercise8_2 (pos = 7):
## 
##     管理者, 评分
```

```r
kruskal.test(评分~管理者)
```

```
## 
## 	Kruskal-Wallis rank sum test
## 
## data:  评分 by 管理者
## Kruskal-Wallis chi-squared = 10.753, df = 2, p-value = 0.004623
```
 p-value = 0.004623<0.05，则拒绝H₀，认为并非所有总体都相同；

## 8.3 某家店制造公司准备购进一批电池，现有A，B，C三个电池生产企业愿意供货，为此校他们生产的电池质量，从每个企业各随机抽取5节电池
### 8.3.1分析3个企业生产的电池平均寿命之间有无显著差异(α=0.05)，并分析效应量。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 9e2d5e7dc3421c6729ae8c9342ec21cc7f07184b
```

```
## [1] "exercise8_3"
```

```r
exercise8_3
```

```
##    企业 电池寿命
## 1     A       50
## 2     A       50
## 3     A       43
## 4     A       40
## 5     A       39
## 6     B       32
## 7     B       28
## 8     B       30
## 9     B       34
## 10    B       26
## 11    C       45
## 12    C       42
## 13    C       38
## 14    C       48
## 15    C       40
```

```r
attach(exercise8_3)
model_3w<-aov(电池寿命~企业)
summary(model_3w)
```

```
##             Df Sum Sq Mean Sq F value  Pr(>F)    
## 企业         2  615.6  307.80   17.07 0.00031 ***
## Residuals   12  216.4   18.03                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

 H₀:3个企业生产的电池平均寿命之间无显著差异
 H₁:3个企业生产的电池平均寿命之间有显著差异
 由分析结果可知，p=0.00031<0.05，拒绝H₀，3个企业生产的电池平均寿命之间有显著差异。

```r
library(DescTools)
model_3w<-aov(电池寿命~企业)
EtaSq(model_3w,anova=T)
```

```
##              eta.sq eta.sq.part    SS df        MS        F            p
## 企业      0.7399038   0.7399038 615.6  2 307.80000 17.06839 0.0003096019
## Residuals 0.2600962          NA 216.4 12  18.03333       NA           NA
```
 由效应量结果$\eta^2$=0.7399038可知，组间差异较大。 

### 8.3.2如果有差异，用HSD方法检验哪些企业之间有差异。

```r
PostHocTest(model_3w,method="hsd")
```

```
## 
##   Posthoc multiple comparisons of means : Tukey HSD 
##     95% family-wise confidence level
## 
## $企业
##      diff     lwr.ci    upr.ci    pval    
## B-A -14.4 -21.565255 -7.234745 0.00046 ***
## C-A  -1.8  -8.965255  5.365255 0.78473    
## C-B  12.6   5.434745 19.765255 0.00140 ** 
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```
 H₀:$n_i$=$n_j$
 H₁:$n_i$≠$n_j$
 由HSD分析结果可知：
 B-A的p-value=0.00046<0.05，拒绝H₀，认为B企业与A企业之间有显著差异；
 C-A的p-value=0.78473>0.05，不拒绝H₀，不能认为C企业与A企业之间有显著差异；
 C-B的p-value=0.00140<0.05，拒绝H₀，认为C企业与B企业之间有显著差异；


## 8.4有5个不同品种的种子和4个不同的施肥方案。在20块同样面积的土地上分别采用5个不同品种的种子和4个不同的施肥方案进行试验

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_4.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_4.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## bbd0d15f5673e2a9416059666c427b32303950ab
```

```
## [1] "exercise8_4"
```

```r
exercise8_4
```

```
##     品种  施肥方案 收获量
## 1  品种1 施肥方案1   12.0
## 2  品种1 施肥方案2    9.5
## 3  品种1 施肥方案3   10.4
## 4  品种1 施肥方案4    9.7
## 5  品种2 施肥方案1   13.7
## 6  品种2 施肥方案2   11.5
## 7  品种2 施肥方案3   12.4
## 8  品种2 施肥方案4    9.6
## 9  品种3 施肥方案1   14.3
## 10 品种3 施肥方案2   12.3
## 11 品种3 施肥方案3   11.4
## 12 品种3 施肥方案4   11.1
## 13 品种4 施肥方案1   14.2
## 14 品种4 施肥方案2   14.0
## 15 品种4 施肥方案3   12.5
## 16 品种4 施肥方案4   12.0
## 17 品种5 施肥方案1   13.0
## 18 品种5 施肥方案2   14.0
## 19 品种5 施肥方案3   13.1
## 20 品种5 施肥方案4   11.4
```

### 8.4.1检验不同品种和施肥量方案对产量的影响是否显著（α=0.05）
 H₀：不同品种和施肥量方案对产量的影响不显著
 H₁：不同品种和施肥量方案对产量的影响显著

```r
attach(exercise8_4)
model_2wm<-aov(收获量~品种+施肥方案)
summary(model_2wm)
```

```
##             Df Sum Sq Mean Sq F value  Pr(>F)   
## 品种         4 19.067   4.767   7.240 0.00332 **
## 施肥方案     3 18.182   6.061   9.205 0.00195 **
## Residuals   12  7.901   0.658                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```
 分析：品种p-value=0.00332<0.05，施肥方案p-value=0.00195 <0.05则拒绝H₀，认为不同品种和施肥量方案对产量的影响显著

### 8.4.2计算偏效应量并进行分析

```r
model_2wm<-aov(收获量~品种+施肥方案)
library(DescTools)
EtaSq(model_2wm,anova=T)
```

```
##              eta.sq eta.sq.part      SS df        MS        F          p
## 品种      0.4223081   0.7070231 19.0670  4 4.7667500 7.239716 0.00331519
## 施肥方案  0.4026955   0.6970766 18.1815  3 6.0605000 9.204658 0.00194911
## Residuals 0.1749964          NA  7.9010 12 0.6584167       NA         NA
```
 品种$\eta^2$=0.4223081，则表明组间差异较大
 施肥方案$\eta^2$= 0.4026955，则表明组间差异较大

## 8.5 城市道路交通管理部门为研究不同路段和不同时间段对行车时间的影响，让一名交通警察分别在3个路段和高峰期与非高峰期亲自驾车进行实验，通过实验并获得30个行车时间数据。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_5.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_5.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## e1638c0b6b78b8e8d20aa2f1039cb4ec4cec0f67
```

```
## [1] "exercise8_5"
```

```r
head(exercise8_5,15)
```

```
##      时段  路段 行车时间
## 1  高峰期 路段1     36.5
## 2  高峰期 路段1     34.1
## 3  高峰期 路段1     37.2
## 4  高峰期 路段1     35.6
## 5  高峰期 路段1     38.0
## 6  高峰期 路段2     28.1
## 7  高峰期 路段2     29.9
## 8  高峰期 路段2     32.2
## 9  高峰期 路段2     31.5
## 10 高峰期 路段2     30.1
## 11 高峰期 路段3     32.4
## 12 高峰期 路段3     33.0
## 13 高峰期 路段3     36.2
## 14 高峰期 路段3     35.5
## 15 高峰期 路段3     35.1
```

### 8.5.1分析路段时段以及路段和时段的交互作用对行车时间的影响（α=0.05）

```r
attach(exercise8_5)
fit<- aov(行车时间~时段 + 路段 + 时段:路段)
summary(fit)
```

```
##             Df Sum Sq Mean Sq F value   Pr(>F)    
## 时段         1 288.30  288.30  70.331 1.36e-08 ***
## 路段         2 180.51   90.26  22.018 3.71e-06 ***
## 时段:路段    2   0.02    0.01   0.003    0.997    
## Residuals   24  98.38    4.10                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```
 检验时段的假设：
 H₀:时段对行车时间无显著影响
 H₁:时段对行车时间有显著影响

 检验路段的假设：
 H₀:路段对行车时间无显著影响
 H₁:路段对行车时间有显著影响

 检验时段与路段交互作用的假设：
 H₀:时段和路段的交互作用对行车时间无显著影响
 H₁:时段和路段的交互作用对行车时间有显著影响

 由交互效应方差分析的结果可知：

 时段$P_a$=1.36*10^(-8)<0.05,拒绝H₀，认为时段对行车时间有显著影响。


 路段$P_b$=3.71*10^(-6)<0.05,拒绝H₀，认为路段对行车时间有显著影响。


 时段和路段的交互作用$P_ab$=0.997>0.05,不拒绝H₀，即不认为时段和路段的交互作用对行车时间有显著影响。


### 8.5.2计算偏效应量并进行分析。


```r
model_5wi<-aov(行车时间~时段 + 路段 + 时段:路段,data=exercise8_5)
library(DescTools)
EtaSq(model_5wi,anova=T)
```

```
##                 eta.sq  eta.sq.part       SS df         MS            F
## 时段      5.082696e-01 0.7455777387 288.3000  1 288.300000 70.331368164
## 路段      3.182453e-01 0.6472503358 180.5147  2  90.257333 22.018459036
## 时段:路段 4.231172e-05 0.0002438925   0.0240  2   0.012000  0.002927424
## Residuals 1.734428e-01           NA  98.3800 24   4.099167           NA
##                      p
## 时段      1.355779e-08
## 路段      3.711926e-06
## 时段:路段 9.970772e-01
## Residuals           NA
```
 
 由交互作用效应量分析结果可知：
 时段的$\eta^2$(偏效应量)=0.7455777387，即组间差异较大。
 路段的$\eta^2$=0.6472503358，即组间差异较大。
 时段和路段的交互作用的$\eta^2$=0.0002438925，即组间差异较小。

## 8.6为检验广告媒体和广告方案对产品销量的影响，一家营销公司做了一项实验，考察三种广告方案和两种广告媒体，获得的数据如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_6.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_6.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 5b1ecab9009bb13f7dceaf982781eee887ab1e9c
```

```
## [1] "exercise8_6"
```

```r
exercise8_6
```

```
##    广告方案 广告媒体 销售量
## 1         A     报纸      8
## 2         A     报纸     12
## 3         A     电视     12
## 4         A     电视      8
## 5         B     报纸     22
## 6         B     报纸     14
## 7         B     电视     26
## 8         B     电视     30
## 9         C     报纸     10
## 10        C     报纸     18
## 11        C     电视     18
## 12        C     电视     14
```
### 8.6.1检验广告方案，广告媒体及其相互作用对销售量的影响是否显著（α=0.05）

 H₀：广告方案对销售量的影响不显著
 H₁：广告方案对销售量的影响显著

 H₀：广告媒体对销售量的影响不显著
 H₁：广告媒体对销售量的影响显著

 H₀：交互效应对销售量的影响不显著
 H₁：交互效应对销售量的影响显著

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_6.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_6.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 5b1ecab9009bb13f7dceaf982781eee887ab1e9c
```

```
## [1] "exercise8_6"
```

```r
mode2<-aov(销售量~广告方案+广告媒体+广告方案:广告媒体,data=exercise8_6)
summary(mode2)
```

```
##                   Df Sum Sq Mean Sq F value Pr(>F)  
## 广告方案           2    344     172   10.75 0.0104 *
## 广告媒体           1     48      48    3.00 0.1340  
## 广告方案:广告媒体  2     56      28    1.75 0.2519  
## Residuals          6     96      16                 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

```r
mode2$coefficients
```

```
##            (Intercept)              广告方案B              广告方案C 
##            1.00000e+01            8.00000e+00            4.00000e+00 
##           广告媒体电视 广告方案B:广告媒体电视 广告方案C:广告媒体电视 
##           -2.56395e-15            1.00000e+01            2.00000e+00
```
 分析:关于广告方案的p-value=0.0104<0.05，则拒绝H₀，认为广告方案对销售量的影响显著；
 关于广告媒体的p-value=0.1340>0.05，则不能拒绝H₀，即不能认为广告媒体对销售量的影响显著；
 交互效应 p-value=0.251>0.05，则不能拒绝H₀，即不能认为交互效应对销售量的影响不显著


### 8.6.2计算偏效应量并进行分析

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_6.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch8/exercise8_6.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 5b1ecab9009bb13f7dceaf982781eee887ab1e9c
```

```
## [1] "exercise8_6"
```

```r
model_2wi<-aov (销售量~广告方案+广告媒体+广告方案:广告媒体,data=exercise8_6)
library(DescTools) 
EtaSq(model_2wi,anova=T) 
```

```
##                       eta.sq eta.sq.part  SS df  MS     F          p
## 广告方案          0.63235294   0.7818182 344  2 172 10.75 0.01038618
## 广告媒体          0.08823529   0.3333333  48  1  48  3.00 0.13397460
## 广告方案:广告媒体 0.10294118   0.3684211  56  2  28  1.75 0.25193177
## Residuals         0.17647059          NA  96  6  16    NA         NA
```
 分析:结果表明，在排除广告媒体和交互效应的影响后，广告方案解释了销售量误差的63.24%;
 在排除广告方案和交互效应的影响后，广告媒体解释了销售量误差的8.82%;
 在排除广告媒体和广告方案的影响后，交互效应解释了销售量误差的10.29%。

# 第九章 一元线性回归
## 9.1 下面是我国31地区2013年的居民消费水平和人均GDP数据。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch9/exercise9_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch9/exercise9_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## f7aee389fcd88b3495fde7905a75494f86435d22
```

```
## [1] "exercise9_1"
```

```r
head(exercise9_1,10)
```

```
##            地区 居民消费水平 人均GDP
## 1        北京市        33337   94648
## 2        天津市        26261  100105
## 3        河北省        11557   38909
## 4        山西省        12078   34984
## 5  内蒙古自治区        17168   67836
## 6        辽宁省        20156   61996
## 7        吉林省        13676   47428
## 8      黑龙江省        12978   37697
## 9        上海市        39223   90993
## 10       江苏省        23585   75354
```

### 9.1.1绘制散点图，判断人均GDP与居民消费水平之间的关系，并计算相关系数分析其关系强度。

```r
library(car)
scatterplot(居民消费水平~人均GDP,data=exercise9_1,col="black",pch=19,xlab="人均GDP",ylab="居民消费水平",cex.lab=0.8)
```

<img src="112_files/figure-html/unnamed-chunk-146-1.png" width="384" />

```r
cor(exercise9_1[,2],exercise9_1[,3])
```

```
## [1] 0.9240374
```

  结论;散点图显示，人均GDP增加，居民消费水平也随之增加。二者的观测点分布在一条直线周围，因而具有正的线性相关关系。人均GDP与居民消费水平之间的相关系数为0.9240374，所以两者之间具有较强的相关性。

### 9.1.2以居民消费水平为因变量、人均GDP为自变量建立回归模型，并对回归模型进行综合评价。

```r
model<-lm(居民消费水平~人均GDP,data=exercise9_1)
summary(model)
```

```
## 
## Call:
## lm(formula = 居民消费水平 ~ 人均GDP, data = exercise9_1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6462.7 -1330.4   133.7  1083.7  9409.5 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 7.514e+02  1.268e+03   0.592    0.558    
## 人均GDP     3.194e-01  2.454e-02  13.016 1.23e-13 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2819 on 29 degrees of freedom
## Multiple R-squared:  0.8538,	Adjusted R-squared:  0.8488 
## F-statistic: 169.4 on 1 and 29 DF,  p-value: 1.227e-13
```

```r
confint(model,level=0.95)
```

```
##                     2.5 %       97.5 %
## (Intercept) -1842.7681829 3345.6541085
## 人均GDP         0.2692021    0.3695731
```

```r
anova(model)
```

```
## Analysis of Variance Table
## 
## Response: 居民消费水平
##           Df     Sum Sq    Mean Sq F value    Pr(>F)    
## 人均GDP    1 1346327123 1346327123  169.42 1.227e-13 ***
## Residuals 29  230454442    7946705                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

  综合评价;回归系数为0.3194，对回归系数进行显著性检验，其P值=1.227x10^(-13)< 0.05,所以两者之间的线性关系显著。对模型进行拟合度检验，P值=0.227x10^ (-13)<0.05，证明模型拟合效果很好。
  
## 9.2从某一行业中随机抽取12家企业，得到产量与生产费用数据如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch9/exercise9_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch9/exercise9_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## d18c3eb3e8b7a797b07869ae59e5d5fec1566013
```

```
## [1] "exercise9_2"
```

```r
exercise9_2
```

```
##    企业编号 产量 生产费用
## 1         1   40      130
## 2         2   42      150
## 3         3   50      155
## 4         4   55      140
## 5         5   65      150
## 6         6   78      154
## 7         7   84      165
## 8         8  100      170
## 9         9  116      167
## 10       10  125      180
## 11       11  130      175
## 12       12  140      185
```

### 9.2.1绘制产量与生产费用的散点图，判断二者之间的关系形态。

```r
library(car)
attach(exercise9_2)
scatterplot(产量~生产费用,data=exercise9_1,col="black",pch=19,xlab="生产费用",ylab="产量",cex.lab=0.8)
```

<img src="112_files/figure-html/unnamed-chunk-149-1.png" width="384" />


  结论：散点图显示，随着生产费用增加，产量也随之增加。二者的观测点分布在一条直线周围，因而具有正的线性相关关系。


### 9.2.2计算产量与生产费用之间的线性相关系数，对相关系数的显著性进行检验，并解释二者之间的关系强度

```r
cor(exercise9_2[,2],exercise9_2[,3]) 
```

```
## [1] 0.9202324
```

```r
cor.test(exercise9_2[,2],exercise9_2[,3])
```

```
## 
## 	Pearson's product-moment correlation
## 
## data:  exercise9_2[, 2] and exercise9_2[, 3]
## t = 7.4355, df = 10, p-value = 2.222e-05
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7339428 0.9777578
## sample estimates:
##       cor 
## 0.9202324
```
  
  结论：产量和生产费用之间的相关系数为0.9202324，表明两者之间具有很强的相关性对相关系数进行检验，P值=2.222(*)10^(-5)<0.05，拒绝原假设，即认为两变量之间线性关系显著。

## 9.3随机抽取10家航空公司，对其最近一年的航班准点率和顾客投诉次数进行调查，所得数据如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch9/exercise9_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch9/exercise9_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## a87a6dc3de8fe3800845c8b8ea78fa98c890e06e
```

```
## [1] "exercise9_3"
```

```r
exercise9_3
```

```
##    航空公司编号 航班准点率 投诉次数
## 1             1       81.8       21
## 2             2       76.6       58
## 3             3       76.6       85
## 4             4       75.7       68
## 5             5       73.8       74
## 6             6       72.2       93
## 7             7       71.2       72
## 8             8       70.8      122
## 9             9       91.4       18
## 10           10       68.5      125
```
### 9.3.1用航班准点率作自变量，顾客投诉次数作因变量，求出估计的回归方程，并解释回归系数的意义。

```r
model3<-lm(投诉次数~航班准点率,data=exercise9_3)
model3
```

```
## 
## Call:
## lm(formula = 投诉次数 ~ 航班准点率, data = exercise9_3)
## 
## Coefficients:
## (Intercept)   航班准点率  
##     430.189       -4.701
```

  结论：估计的回归方程为$\hat{y}$=-4.701x+430.189。回归系数为-4.701，表示航班准点率每提高一个百分点，投诉次数便下降4.7006次。

### 9.3.2检验回归系数的显著性

```r
summary(model3)
```

```
## 
## Call:
## lm(formula = 投诉次数 ~ 航班准点率, data = exercise9_3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -24.678 -11.412  -2.078  16.322  24.615 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 430.1892    72.1548   5.962 0.000337 ***
## 航班准点率   -4.7006     0.9479  -4.959 0.001108 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 18.89 on 8 degrees of freedom
## Multiple R-squared:  0.7545,	Adjusted R-squared:  0.7239 
## F-statistic: 24.59 on 1 and 8 DF,  p-value: 0.001108
```

  结论：检验结果可知F=24.59，P值=0.001108<0.05，所以拒绝原假设，认为两个变量之间线性关系显著。

## 9.3.3如果航班准点率为80%，估计顾客的投诉次数。

```r
p1=(-4.701)*80+430.189
p1
```

```
## [1] 54.109
```

  结论：如果航班准点率为80%，估计顾客的投诉次数为54.109次。

## 9.4随机抽取7家超市，得到其广告费支出和销售额数据如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch9/exercise9_4.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch9/exercise9_4.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 6d82d98537e3bb91fde3bb78503e8f49f679d246
```

```
## [1] "exercise9_4"
```

```r
exercise9_4
```

```
##   超市 广告费支出 销售额
## 1    A          1     19
## 2    B          2     32
## 3    C          4     44
## 4    D          6     40
## 5    E         10     52
## 6    F         14     53
## 7    G         20     54
```

  结论：用广告费支出作自变量x，销售额做因变量y建立回归模型，并对模型进行诊断和评价。

### 在一元线性回归模型中，首先假定y与x之间是线性关系，同时假定eta是期望值为0、方差相等且服从正态分布的独立随机变量。模型诊断就要针对以上问题进行诊断。

```r
model4<-lm(销售额~广告费支出,data=exercise9_4)
par(mfrow=c(2,2),mar=c(2.0,2.0,1.8,1.5),cex=0.8,cex.main=0.6)
plot(model4)
```

<img src="112_files/figure-html/unnamed-chunk-156-1.png" width="384" />

```r
library(car)
durbinWatsonTest(model4)
```

```
##  lag Autocorrelation D-W Statistic p-value
##    1      0.07638099      1.257358   0.068
##  Alternative hypothesis: rho != 0
```

  结论:由NormalQ-Q图可知，该模型残差基本符合正态性假定。由ResidualsvsFitted图可知，广告费支出和销售额之间为线性关系的假定成立。由Scale-Location图可知，该模型关于eta方差齐性的假定基本成立。残差独立性检验中，P值=0.086>0.05，所以不拒绝原假设，显示残差无自相关。

# 第10章 多元线性回归

## 10.1 一家电器销售公司的管理人员认为，每月的销售收入是广告费用的函数，并想通过广告费用对月销售收入进行估计，下面是近8个月的销售收入与广告费用数据：

### 10.1.1用电视广告费用和报纸广告费用作自变量，建立估计的回归方程，并说明回归系数的意义。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch10/exercise10_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch10/exercise10_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## fffc55fa32a54533e3fee71a0c462d48452d3d2b
```

```
## [1] "exercise10_1"
```

```r
exercise10_1
```

```
##   月销售收入 电视广告费用 报纸广告费用
## 1        960           50           15
## 2        900           20           20
## 3        950           40           15
## 4        920           25           25
## 5        950           30           33
## 6        940           35           23
## 7        940           25           42
## 8        940           30           25
```

```r
model1<-lm(月销售收入~电视广告费用+报纸广告费用,data=exercise10_1)
summary(model1)
```

```
## 
## Call:
## lm(formula = 月销售收入 ~ 电视广告费用 + 报纸广告费用, data = exercise10_1)
## 
## Residuals:
##      1      2      3      4      5      6      7      8 
## -6.325 -4.124  6.577 -2.080  6.061 -2.380 -4.197  6.469 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  832.3009    15.7387  52.882 4.57e-08 ***
## 电视广告费用   2.2902     0.3041   7.532 0.000653 ***
## 报纸广告费用   1.3010     0.3207   4.057 0.009761 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 6.426 on 5 degrees of freedom
## Multiple R-squared:  0.919,	Adjusted R-squared:  0.8866 
## F-statistic: 28.38 on 2 and 5 DF,  p-value: 0.001865
```

 令y表示月销售收入，$x_1$表示电视广告费用，$x_2$表示报纸广告费用
 由多元线性回归建模结果可知回归方程为：$\hat{y}$=832.3009+2.2902$x_1$+1.3010$x_2$
 各回归系数的实际意义为：
 $\beta_1$=2.2902表示，在报纸广告费用不变的条件下，电视广告费用每变动1万元，月销售收入平均变动2.2902万元；
 $\beta_2$=1.3010表示，在电视广告费用不变的条件下，报纸广告费用每变动1万元，月销售收入平均变动1.3010万元。

### 10.1.2对回归模型做综合评估。


```r
confint(model1,level=0.95)
```

```
##                    2.5 %     97.5 %
## (Intercept)  791.8433275 872.758506
## 电视广告费用   1.5085608   3.071806
## 报纸广告费用   0.4765994   2.125379
```

```r
anova(model1)
```

```
## Analysis of Variance Table
## 
## Response: 月销售收入
##              Df  Sum Sq Mean Sq F value   Pr(>F)   
## 电视广告费用  1 1664.01 1664.01  40.299 0.001432 **
## 报纸广告费用  1  679.53  679.53  16.457 0.009761 **
## Residuals     5  206.46   41.29                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

 H₀:$\beta_i$=0(自变量$x_i$与因变量y没有线性关系)
 H₁:$\beta_i$≠0(自变量$x_i$与因变量y有线性关系)
 综合评估：对回归系数进行显著性检验，其P值=0.001865<0.05，所以月销售收入与电视广告费用和表示报纸广告费用之间线性关系显著；对模型进行拟合度检验，电视广告费用P值=0.001432<0.05，报纸广告费用P值=0.009761<0.05，证明模型拟合效果很好。


### 10.1.3给定电视广告费用为30万元，报纸广告费用为20万元，求月销售收入95%的置信区间和预测区间。

```r
model1<-lm(月销售收入~电视广告费用+报纸广告费用,data=exercise10_1)
x0<-data.frame(电视广告费用=30,报纸广告费用=20)
predict(model1,data.frame(电视广告费用=30,报纸广告费用=20),interval="confidence",level=0.95)
```

```
##        fit      lwr      upr
## 1 927.0262 919.4121 934.6403
```

```r
predict(model1,data.frame(电视广告费用=30,报纸广告费用=20),interval="prediction",level=0.95)
```

```
##        fit      lwr      upr
## 1 927.0262 908.8376 945.2148
```

  分析：由逐步回归预测结果可知：在电视广告费用为30万元和报纸广告费用为20万元时，月销售收入95%的置信区间为[919.4121,934.6403]和预测区间[908.8376,945.2148]。

## 10.2某农场通过试验取得早稻收获量和春季降雨量和春季温度的数据如下

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch10/exercise10_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch10/exercise10_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## f690e3efed651c76463502cc3d62a187f83a9f46
```

```
## [1] "exercise10_2"
```

```r
exercise10_2
```

```
##   收获量 降雨量 温度
## 1   2250     25    6
## 2   3450     33    8
## 3   4500     45   10
## 4   6750    105   13
## 5   7200    110   14
## 6   7500    115   16
## 7   8250    120   17
```

### 10.2.1建立早稻收获量对春季降雨量和春季温度的二元线性回归方程，并对回归模型的线性关系和回归系数进行检验（α=0.05），你认为模型中是否存在多重共线性

### 建立回归方程

```r
model2<-lm(收获量~降雨量+温度,data=exercise10_2)
summary(model2)
```

```
## 
## Call:
## lm(formula = 收获量 ~ 降雨量 + 温度, data = exercise10_2)
## 
## Residuals:
##        1        2        3        4        5        6        7 
## -275.101   90.464  216.483  140.280  150.676 -316.599   -6.203 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)  
## (Intercept)   -0.591    505.004  -0.001   0.9991  
## 降雨量        22.387      9.601   2.332   0.0801 .
## 温度         327.672     98.798   3.317   0.0295 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 261.4 on 4 degrees of freedom
## Multiple R-squared:  0.9913,	Adjusted R-squared:  0.987 
## F-statistic: 228.4 on 2 and 4 DF,  p-value: 7.532e-05
```

 令y=收获量，x~1~=降雨量，x~2~=温度，则回归方程为$\hat{y}$=-0.591+22.387$x_1$+327.672$x_2$
 回归系数显著性检验：
 H₀：线性关系不显著
 H₁：β~1~,β~2~至少有一个不等于0
 降雨量p-value=0.0801>0.05，温度p-value=0.0295<0.05，则降水量的影响是不显著的，温度的影响是显著的
 多重共线性：
 H₀：自变量x~i~与因变量y没有线性关系
 H₁：自变量x~i~与因变量y有线性关系

```r
library(psych)
```

```
## Warning: 程辑包'psych'是用R版本3.6.2 来建造的
```

```
## 
## 载入程辑包：'psych'
```

```
## The following object is masked from 'package:car':
## 
##     logit
```

```
## The following objects are masked from 'package:DescTools':
## 
##     AUC, ICC, SD
```

```
## The following object is masked from 'package:plotrix':
## 
##     rescale
```

```r
corr.test(exercise10_2,use="complete")
```

```
## Call:corr.test(x = exercise10_2, use = "complete")
## Correlation matrix 
##        收获量 降雨量 温度
## 收获量   1.00   0.98 0.99
## 降雨量   0.98   1.00 0.97
## 温度     0.99   0.97 1.00
## Sample Size 
## [1] 7
## Probability values (Entries above the diagonal are adjusted for multiple tests.) 
##        收获量 降雨量 温度
## 收获量      0      0    0
## 降雨量      0      0    0
## 温度        0      0    0
## 
##  To see confidence intervals of the correlations, print with the short=FALSE option
```
        收获量 降雨量 温度
收获量   1.00   0.98 0.99
降雨量   0.98   1.00 0.97
温度     0.99   0.97 1.00


### 10.2.2比较降雨量和温度在预测收获量中的相对重要性

```r
attach(exercise10_2)
```

```
## The following object is masked from exercise8_4:
## 
##     收获量
```

```r
model2<-lm(收获量~降雨量+温度,data=exercise10_2)
library(lm.beta)
model1.beta<-lm.beta(model1)
summary(model1.beta)
```

```
## 
## Call:
## lm(formula = 月销售收入 ~ 电视广告费用 + 报纸广告费用, data = exercise10_1)
## 
## Residuals:
##      1      2      3      4      5      6      7      8 
## -6.325 -4.124  6.577 -2.080  6.061 -2.380 -4.197  6.469 
## 
## Coefficients:
##              Estimate Standardized Std. Error t value Pr(>|t|)    
## (Intercept)  832.3009       0.0000    15.7387  52.882 4.57e-08 ***
## 电视广告费用   2.2902       1.1535     0.3041   7.532 0.000653 ***
## 报纸广告费用   1.3010       0.6213     0.3207   4.057 0.009761 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 6.426 on 5 degrees of freedom
## Multiple R-squared:  0.919,	Adjusted R-squared:  0.8866 
## F-statistic: 28.38 on 2 and 5 DF,  p-value: 0.001865
```

 分析：结果显示各标准化回归系数为：0.4146，0.5896，β~2~的相对重要性大于β~1~,即降雨量对收获量的预测更重要。


## 10.3 为分析影响不良贷款的因素，一家商业银行在所属的多家分行中随机抽取25家，得到不良贷款、贷款余额、应收贷款、贷款项目个数、固定资产投资等有关数据如下：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch10/exercise10_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch10/exercise10_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## c5a62c154e47b59e320e95ff844567201f88859d
```

```
## [1] "exercise10_3"
```

```r
head(exercise10_3,10)
```

```
##    不良贷款 贷款余额 应收贷款 贷款项目个数 固定资产投资
## 1       0.9     67.3      6.8            5         51.9
## 2       1.1    111.3     19.8           16         90.9
## 3       4.8    173.0      7.7           17         73.7
## 4       3.2     80.8      7.2           10         14.5
## 5       7.8    199.7     16.5           19         63.2
## 6       2.7     16.2      2.2            1          2.2
## 7       1.6    107.4     10.7           17         20.2
## 8      12.5    185.4     27.1           18         43.8
## 9       1.0     96.1      1.7           10         55.9
## 10      2.6     72.8      9.1           14         64.3
```

### 10.3.1用不良贷款作因变量，建立多元线性回归模型。

```r
attach(exercise10_3)
```

```
## The following object is masked from exercise2_4:
## 
##     固定资产投资
```

```r
model3=lm(不良贷款~贷款余额+应收贷款+贷款项目个数+固定资产投资,data=exercise10_3)
summary(model3)
```

```
## 
## Call:
## lm(formula = 不良贷款 ~ 贷款余额 + 应收贷款 + 贷款项目个数 + 
##     固定资产投资, data = exercise10_3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.9198 -0.9507 -0.2880  1.0334  3.1037 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)   
## (Intercept)  -1.02164    0.78237  -1.306  0.20643   
## 贷款余额      0.04004    0.01043   3.837  0.00103 **
## 应收贷款      0.14803    0.07879   1.879  0.07494 . 
## 贷款项目个数  0.01453    0.08303   0.175  0.86285   
## 固定资产投资 -0.02919    0.01507  -1.937  0.06703 . 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.779 on 20 degrees of freedom
## Multiple R-squared:  0.7976,	Adjusted R-squared:  0.7571 
## F-statistic:  19.7 on 4 and 20 DF,  p-value: 1.035e-06
```

 分析：贷款余额用建立的多元线性回归方程为$\hat{y}=0.04X_1+0.15X_2+0.014X_3-0.03X_4-1.02$


### 10.3.2分析模型中是否存在共线性。
### 采用对模型中各自变量之间的相关系数进行检验的方法识别多重共线性

```r
library(psych)
corr.test(exercise10_3[2:5],use="complete")
```

```
## Warning in abbreviate(rownames(r), minlength = minlength): abbreviate不适用于非
## ASCII字元
```

```
## Warning in abbreviate(colnames(r), minlength = minlength): abbreviate不适用于非
## ASCII字元
```

```
## Call:corr.test(x = exercise10_3[2:5], use = "complete")
## Correlation matrix 
##              贷款余额 应收贷款 贷款项目个数 固定资产投资
## 贷款余额         1.00     0.68         0.85         0.78
## 应收贷款         0.68     1.00         0.59         0.47
## 贷款项目个数     0.85     0.59         1.00         0.75
## 固定资产投资     0.78     0.47         0.75         1.00
## Sample Size 
## [1] 25
## Probability values (Entries above the diagonal are adjusted for multiple tests.) 
##              贷款余额 应收贷款 贷款项目个数 固定资产投资
## 贷款余额            0     0.00            0         0.00
## 应收贷款            0     0.00            0         0.02
## 贷款项目个数        0     0.00            0         0.00
## 固定资产投资        0     0.02            0         0.00
## 
##  To see confidence intervals of the correlations, print with the short=FALSE option
```


### 10.3.3用逐步回归方法建立回归模型

```r
model3.1=step(model3)
```

```
## Start:  AIC=33.22
## 不良贷款 ~ 贷款余额 + 应收贷款 + 贷款项目个数 + 固定资产投资
## 
##                Df Sum of Sq     RSS    AIC
## - 贷款项目个数  1     0.097  63.376 31.255
## <none>                       63.279 33.217
## - 应收贷款      1    11.168  74.447 35.280
## - 固定资产投资  1    11.868  75.147 35.514
## - 贷款余额      1    46.594 109.873 45.011
## 
## Step:  AIC=31.26
## 不良贷款 ~ 贷款余额 + 应收贷款 + 固定资产投资
## 
##                Df Sum of Sq     RSS    AIC
## <none>                       63.376 31.255
## - 应收贷款      1    11.333  74.709 33.368
## - 固定资产投资  1    12.147  75.523 33.639
## - 贷款余额      1    69.939 133.315 47.846
```

  分析:从逐步回归结果中，选择全部自变量时AIC=33.22，去掉变量“贷款项目个数”之后ACI=31.26，之后去掉任何一个解释变量ACI都会变大，故最终模型中保留“应收账款”、“固定资产投资”、“贷款余额”三个解释变量。


### 10.3.4比较4个自变量在不良贷款中的相对重要性

```r
library(lm.beta)
model3.beta=lm.beta(model3)
summary(model3.beta)
```

```
## 
## Call:
## lm(formula = 不良贷款 ~ 贷款余额 + 应收贷款 + 贷款项目个数 + 
##     固定资产投资, data = exercise10_3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.9198 -0.9507 -0.2880  1.0334  3.1037 
## 
## Coefficients:
##              Estimate Standardized Std. Error t value Pr(>|t|)   
## (Intercept)  -1.02164      0.00000    0.78237  -1.306  0.20643   
## 贷款余额      0.04004      0.89131    0.01043   3.837  0.00103 **
## 应收贷款      0.14803      0.25982    0.07879   1.879  0.07494 . 
## 贷款项目个数  0.01453      0.03447    0.08303   0.175  0.86285   
## 固定资产投资 -0.02919     -0.32492    0.01507  -1.937  0.06703 . 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.779 on 20 degrees of freedom
## Multiple R-squared:  0.7976,	Adjusted R-squared:  0.7571 
## F-statistic:  19.7 on 4 and 20 DF,  p-value: 1.035e-06
```

 分析：各标准化的回归系数为：$\hat{\beta_1}=0.89131，\hat{\beta_2}=0.25982 ，\hat{\beta_3}= 0.03447 ，\hat{\beta_4}$= -0.32492 -0.32492$,所以贷款余额是预测不良贷款最重要的变量。

### 10.3.5用anova和AIC两种方法对模型进行比较和分析

```r
model3_1=lm(不良贷款~贷款余额+应收贷款+贷款项目个数+固定资产投资,data=exercise10_3)
model3_2=lm(不良贷款~贷款余额+应收贷款+固定资产投资,data=exercise10_3)
anova(model3_2,model3_1)
```

```
## Analysis of Variance Table
## 
## Model 1: 不良贷款 ~ 贷款余额 + 应收贷款 + 固定资产投资
## Model 2: 不良贷款 ~ 贷款余额 + 应收贷款 + 贷款项目个数 + 固定资产投资
##   Res.Df    RSS Df Sum of Sq      F Pr(>F)
## 1     21 63.376                           
## 2     20 63.279  1  0.096877 0.0306 0.8629
```

```r
AIC(model3_2,model3_1)
```

```
##          df      AIC
## model3_2  5 104.2022
## model3_1  6 106.1639
```

 分析:p-value=0.8629>0.05,表明两个变量之间无显著差异。

## 10.4为分析某行业中薪水有无性别歧视。从该行业中速机抽取15名员工

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch10/exercise10_4.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch10/exercise10_4.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 5d61c760a4bb4a86612997d30d8186b6d082de9d
```

```
## [1] "exercise10_4"
```

```r
exercise10_4
```

```
##    月薪 工龄 性别
## 1  6548  3.2   男
## 2  6629  3.8   男
## 3  6011  2.7   女
## 4  6229  3.4   女
## 5  6746  3.6   男
## 6  6528  4.1   男
## 7  6018  3.8   女
## 8  6190  3.4   女
## 9  6551  3.3   男
## 10 5985  3.2   女
## 11 6610  3.5   男
## 12 6432  2.9   男
## 13 6215  3.3   女
## 14 5990  2.8   女
## 15 6585  3.5   男
```

### 10.4.1建立月薪与工龄的一元回归模型

```r
model<-lm(月薪~工龄,data=exercise10_4)
summary(model)
```

```
## 
## Call:
## lm(formula = 月薪 ~ 工龄, data = exercise10_4)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -474.90 -152.54  -63.05  218.46  318.53 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   5249.7      587.1   8.941 6.48e-07 ***
## 工龄           327.2      173.3   1.887   0.0817 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 248.4 on 13 degrees of freedom
## Multiple R-squared:  0.2151,	Adjusted R-squared:  0.1547 
## F-statistic: 3.562 on 1 and 13 DF,  p-value: 0.08165
```

 分析：令y=月薪，x=工龄，则回归方程为：$\hat{y}$=327.2x+5249.7


### 10.4.2建立月薪与工龄和性别的二元回归模型

```r
model4<-lm(月薪~工龄+性别,data=exercise10_4)
summary(model4)
```

```
## 
## Call:
## lm(formula = 月薪 ~ 工龄 + 性别, data = exercise10_4)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -136.697  -67.380    1.351   54.888  154.863 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  6190.74     253.71  24.401 1.35e-11 ***
## 工龄          111.22      72.08   1.543    0.149    
## 性别女       -458.68      53.46  -8.580 1.82e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 96.79 on 12 degrees of freedom
## Multiple R-squared:   0.89,	Adjusted R-squared:  0.8717 
## F-statistic: 48.54 on 2 and 12 DF,  p-value: 1.773e-06
```

 令 y=月薪，$x_1$=工龄，$x_2$=性别女，则回归方程为：$\hat{y}=111.22x_1+-458.68x_2+6190.74$


### 10.4.3对两个模型进行比较，看看引入性别这一变量对预测月薪是否有用
##### H₀：β~2~=0
##### H₁：β~2~≠0

```r
model1<-lm(月薪~工龄+性别,data=exercise10_4) 
model2<-lm(月薪~工龄,data=exercise10_4)
anova(model2,model1)
```

```
## Analysis of Variance Table
## 
## Model 1: 月薪 ~ 工龄
## Model 2: 月薪 ~ 工龄 + 性别
##   Res.Df    RSS Df Sum of Sq     F    Pr(>F)    
## 1     13 802137                                 
## 2     12 112423  1    689714 73.62 1.823e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

 分析：p-value=1.823e-06<0.05,则拒绝原假设，认为引入性别这一变量对预测月薪是有用。



# 第11章 时间序列预测
### 11.1 根据2006-2015年中国工业生产者出厂价格指数(PPI)数据(上年=100)，采用指数平滑法预测2016年的PPI，并对实际值和预测值绘图进行比较。

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_1.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_1.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 5be7c03b9874aefa83335d70a8f8a5bff4cba71e
```

```
## [1] "exercise11_1"
```

```r
exercise11_1<-ts(exercise11_1,start=2006)
par(mai=c(0.6,0.6,0.12,0.1) ,cex=0.7)
plot(exercise11_1[,2],type='o',xlab="（a）年份",ylab="PPI")
```

<img src="112_files/figure-html/unnamed-chunk-174-1.png" width="384" />

```r
cpiforecast<-HoltWinters(exercise11_1[,2],beta=FALSE,gamma=FALSE)
library(forecast)
```

```
## Registered S3 method overwritten by 'xts':
##   method     from
##   as.zoo.xts zoo
```

```
## Registered S3 method overwritten by 'quantmod':
##   method            from
##   as.zoo.data.frame zoo
```

```
## Registered S3 methods overwritten by 'forecast':
##   method             from    
##   fitted.fracdiff    fracdiff
##   residuals.fracdiff fracdiff
```

```
## 
## 载入程辑包：'forecast'
```

```
## The following object is masked from 'package:DescTools':
## 
##     BoxCox
```

```r
cpiforecast<-forecast(cpiforecast,h=1)
cpiforecast
```

```
##      Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2016       99.05995 92.90847 105.2114 89.65208 108.4678
```

```r
plot(cpiforecast,type='o',xlab="年份",ylab="PPI",main="")
```

<img src="112_files/figure-html/unnamed-chunk-174-2.png" width="384" />

 分析：图中折线是PPI的观测值，圆点是2016年的预测值，灰色区域是预测值的置信区间，其中浅灰色区域是95%的置信区间，深灰色区域是80%的置信区间。


## 11.2根据1990-2010年我国原油产量数据，分别采用一元线性回归模型和Holt指数平滑模型预测2011年的原油产量，并绘制残差图对两种方法的预测效果进行比较。
### 一元线性回归模型

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 8c769d50d9e7254343c34927f053f77812860629
```

```
## [1] "exercise11_2"
```

```r
fit<-lm(原油产量~年份,data=exercise11_2)
summary(fit)
```

```
## 
## Call:
## lm(formula = 原油产量 ~ 年份, data = exercise11_2)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -477.2 -251.6   19.0  157.7  806.9 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -571251.54   23267.81  -24.55 7.44e-16 ***
## 年份            293.90      11.63   25.26 4.39e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 322.8 on 19 degrees of freedom
## Multiple R-squared:  0.9711,	Adjusted R-squared:  0.9696 
## F-statistic: 638.2 on 1 and 19 DF,  p-value: 4.391e-16
```

 分析：由结果可知一元线性回归预测方程为$\hat{Y_t}$=-571251.54+293.90t,则当t=2011时，$\hat{Y}_t$=19781.36。
### Holt指数平滑模型

```r
exercise11_2<-ts(exercise11_2,start=1990)
grainforecast<-HoltWinters(exercise11_2[,2],gamma=FALSE)
grainforecast
```

```
## Holt-Winters exponential smoothing with trend and without seasonal component.
## 
## Call:
## HoltWinters(x = exercise11_2[, 2], gamma = FALSE)
## 
## Smoothing parameters:
##  alpha: 0.7400461
##  beta : 0
##  gamma: FALSE
## 
## Coefficients:
##       [,1]
## a 20041.77
## b   268.00
```

```r
library(forecast)
grainforecast1<-forecast(grainforecast,h=1)
grainforecast1
```

```
##      Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2011       20309.77 19888.91 20730.63 19666.12 20953.42
```

 分析：由结果可知Holt指数平滑模型预测2011年的原油产量为20309.77。

### 绘制残差图对两种方法的预测效果进行比较

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_2.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_2.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 8c769d50d9e7254343c34927f053f77812860629
```

```
## [1] "exercise11_2"
```

```r
predata<-predict(fit,data.frame(年份=1990:2010)); predata#各年的预测值
```

```
##        1        2        3        4        5        6        7        8 
## 13616.44 13910.34 14204.24 14498.15 14792.05 15085.95 15379.86 15673.76 
##        9       10       11       12       13       14       15       16 
## 15967.66 16261.57 16555.47 16849.37 17143.28 17437.18 17731.09 18024.99 
##       17       18       19       20       21 
## 18318.89 18612.80 18906.70 19200.60 19494.51
```

```r
res<-residuals(fit);res#各年的预测残差
```

```
##           1           2           3           4           5           6 
##  214.563636  188.660130    5.756623   25.853117 -184.050390  -80.953896 
##           7           8           9          10          11          12 
##  353.542597  400.339091  132.335584 -261.567922 -255.471429 -453.474935 
##          13          14          15          16          17          18 
## -443.278442 -477.181948 -143.785455  110.311039  157.707532   19.004026 
##          19          20          21 
##  136.400519 -251.602987  806.893506
```

```r
residual1<-grainforecast1$residuals
fit<-lm(原油产量~年份,data=exercise11_2)
residual2<-fit$residuals
#par(mai=c(0.4,0.7,0.1,0.1),cex=0.8)
plot(as.numeric(residual1),ylim=c(-800,800),xlab="",ylab="残差",pch=1)
points(residual2,pch=2,col="red")
abline(h=0)
legend(x="topright",legend=c("Holt模型预测的残差","一元线性回归预测的残差"),pch=1:2,col=c("black","red"),cex=.8)
```

<img src="112_files/figure-html/unnamed-chunk-177-1.png" width="384" />


  分析：从残差图中可以看出，一元线性回归预测的残差和Holt模型预测的残差相差不大，所以选择任意一个模型预测均可。


## 11.3下表是1991-2008年我国财政收入数据：

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_3.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_3.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## 3e9cbff8a0eecc777614d84763a678229b628303
```

```
## [1] "exercise11_3"
```

```r
exercise11_3
```

```
##    年份 财政收入
## 1  1991  3149.48
## 2  1992  3483.37
## 3  1993  4348.95
## 4  1994  5218.10
## 5  1995  6242.20
## 6  1996  7407.99
## 7  1997  8651.14
## 8  1998  9875.95
## 9  1999 11444.08
## 10 2000 13395.23
## 11 2001 16386.04
## 12 2002 18903.64
## 13 2003 21715.25
## 14 2004 26396.47
## 15 2005 31649.29
## 16 2006 38760.20
## 17 2007 51321.78
## 18 2008 61330.35
```

### 分别采用Holt指数平滑模型和指数模型预测2009年的财政收入，并对实际值和预测值绘图进行比较

```r
exercise11_3<-ts(exercise11_3,start=1991)
forecast<-HoltWinters(exercise11_3[,2],gamma=FALSE)
forecast
```

```
## Holt-Winters exponential smoothing with trend and without seasonal component.
## 
## Call:
## HoltWinters(x = exercise11_3[, 2], gamma = FALSE)
## 
## Smoothing parameters:
##  alpha: 0.9367135
##  beta : 1
##  gamma: FALSE
## 
## Coefficients:
##       [,1]
## a 61454.17
## b 10488.85
```

```r
library(forecast)
forecast1<-forecast(grainforecast,h=1)
forecast1
```

```
##      Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2011       20309.77 19888.91 20730.63 19666.12 20953.42
```

```r
par(mai=c(.7,.7,.1,.1),cex=.9)
plot(forecast1,type='o',xlab="年份",ylab="财政收入" ,main="")
```

<img src="112_files/figure-html/unnamed-chunk-179-1.png" width="384" />


 Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
 3167.48       71943.02 69907.34 73978.69 68829.72 75056.32
 分析：采用Holt指数平滑模型预测2009年的财政收入为71943.02。

```r
exercise11_3<-ts(exercise11_3,start=1991)
forecast<-HoltWinters(exercise11_3[,2],beta=FALSE,gamma=FALSE)
forecast
```

```
## Holt-Winters exponential smoothing without trend and without seasonal component.
## 
## Call:
## HoltWinters(x = exercise11_3[, 2], beta = FALSE, gamma = FALSE)
## 
## Smoothing parameters:
##  alpha: 0.9999542
##  beta : FALSE
##  gamma: FALSE
## 
## Coefficients:
##       [,1]
## a 61329.89
```

```r
library(forecast)
forecast1<-forecast(cpiforecast,h=1)
forecast1
```

```
##      Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2016       99.05995 92.90847 105.2114 89.65208 108.4678
```

```r
plot(forecast1,type='o',xlab="年份",ylab="财政收入" ,main="")
```

<img src="112_files/figure-html/unnamed-chunk-180-1.png" width="384" />


 Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95


 3167.48       61329.89 56850.69 65809.09 54479.55 68180.23

 分析：采用指数模型预测2009年的财政收入为61329.89。

## 11.4 下面是某支股票连续35个交易日的收盘价格：分别拟合回归直线二次曲线和三次曲线，并绘制图像对结果进行比较

```r
library(repmis)
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_4.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_4.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## cbfa8c42ceb0ccb96dc5c3ca8439b34a2108e429
```

```
## [1] "exercise11_4"
```

```r
head(exercise11_4,10)
```

```
##    时间 盘价格
## 1     1    372
## 2     2    370
## 3     3    374
## 4     4    375
## 5     5    377
## 6     6    377
## 7     7    374
## 8     8    372
## 9     9    373
## 10   10    372
```

```r
fit=lm(盘价格~时间,data=exercise11_4)  
summary(fit)
```

```
## 
## Call:
## lm(formula = 盘价格 ~ 时间, data = exercise11_4)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -12.0457  -2.8761   0.4779   3.0210  12.3190 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 374.16134    1.75818 212.811  < 2e-16 ***
## 时间         -0.61373    0.08518  -7.205 2.93e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.09 on 33 degrees of freedom
## Multiple R-squared:  0.6113,	Adjusted R-squared:  0.5996 
## F-statistic: 51.91 on 1 and 33 DF,  p-value: 2.928e-08
```

```r
predata<-predict(fit,data.frame(时间=1:35)); predata
```

```
##        1        2        3        4        5        6        7        8 
## 373.5476 372.9339 372.3202 371.7064 371.0927 370.4790 369.8653 369.2515 
##        9       10       11       12       13       14       15       16 
## 368.6378 368.0241 367.4104 366.7966 366.1829 365.5692 364.9555 364.3417 
##       17       18       19       20       21       22       23       24 
## 363.7280 363.1143 362.5006 361.8868 361.2731 360.6594 360.0457 359.4319 
##       25       26       27       28       29       30       31       32 
## 358.8182 358.2045 357.5908 356.9770 356.3633 355.7496 355.1359 354.5221 
##       33       34       35 
## 353.9084 353.2947 352.6810
```

```r
y<-exercise11_4[,2]
x<-1:35
fit1<-lm(y~x+I(x^2))
fit1
```

```
## 
## Call:
## lm(formula = y ~ x + I(x^2))
## 
## Coefficients:
## (Intercept)            x       I(x^2)  
##   381.64416     -1.82715      0.03371
```

```r
predata1<-predict(fit1,data.frame(x=1:35))
predata1
```

```
##        1        2        3        4        5        6        7        8 
## 379.8507 378.1247 376.4661 374.8748 373.3510 371.8947 370.5057 369.1841 
##        9       10       11       12       13       14       15       16 
## 367.9300 366.7432 365.6239 364.5720 363.5875 362.6704 361.8208 361.0385 
##       17       18       19       20       21       22       23       24 
## 360.3237 359.6762 359.0962 358.5836 358.1384 357.7606 357.4503 357.2073 
##       25       26       27       28       29       30       31       32 
## 357.0318 356.9236 356.8829 356.9096 357.0037 357.1652 357.3942 357.6905 
##       33       34       35 
## 358.0543 358.4855 358.9840
```

```r
fit2<-lm(y~x+I(x^2)+I(x^3));fit2
```

```
## 
## Call:
## lm(formula = y ~ x + I(x^2) + I(x^3))
## 
## Coefficients:
## (Intercept)            x       I(x^2)       I(x^3)  
##  372.561669     1.002958    -0.160088     0.003589
```

```r
predata2<-predict(fit2,data.frame(x=1:35))
predata2
```

```
##        1        2        3        4        5        6        7        8 
## 373.4081 373.9559 374.2267 374.2418 374.0229 373.5914 372.9690 372.1772 
##        9       10       11       12       13       14       15       16 
## 371.2374 370.1713 369.0003 367.7459 366.4298 365.0735 363.6984 362.3262 
##       17       18       19       20       21       22       23       24 
## 360.9783 359.6762 358.4416 357.2960 356.2608 355.3576 354.6080 354.0334 
##       25       26       27       28       29       30       31       32 
## 353.6554 353.4956 353.5755 353.9166 354.5404 355.4685 356.7224 358.3236 
##       33       34       35 
## 360.2937 362.6542 365.4266
```

```r
residual2<-fit2$residuals
residual2
```

```
##             1             2             3             4             5 
## -1.4081284292 -3.9559447107 -0.2266507431  0.7582207886  2.9771371991 
##             6             7             8             9            10 
##  3.4085658031  1.0309739155 -0.1771711491  1.7625979242  1.8287484501 
##            11            12            13            14            15 
## -0.0002522566 -0.7459368812  0.5701618912 -0.0734886247 -0.6984211142 
##            16            17            18            19            20 
## -3.3261682625 -2.9782627547 -0.6762372762  1.5583754878 -0.2959571479 
##            21            22            23            24            25 
## -0.2607678685 -3.3575893593 -6.6079543055 -1.0333953923  2.3445546950 
##            26            27            28            29            30 
##  2.5043632712  2.4244976511  5.0834251494  5.4596130810  1.5315287605 
##            31            32            33            34            35 
##  0.2776395027 -3.3235873775 -4.2936845655  0.3458152536 -0.4266206056
```

```r
par(mfrow=c(2,2),mai=c(.6,.6,.4,.1),cex=.5)
plot(1:35,predata,type='o',lty=2,col="blue",xlab="时间",ylab="收盘价格")
lines(exercise11_4[,1],exercise11_4[,2],type='o',pch=19)
legend(x="topright",legend=c("观测值","预测值"),lty=1:5,cex=.7)
plot(1:35,predata1,type='o',lty=2,col="blue",xlab="时间",ylab="收盘价格")
lines(exercise11_4[,1],exercise11_4[,2],type='o',pch=19)
legend(x="topright",legend=c("观测值","预测值"),lty=1:5,cex=.7)
plot(1:35,predata2,type='o',lty=2,col="blue",xlab="时间",ylab="收盘价格")
lines(exercise11_4[,1],exercise11_4[,2],type='o',pch=19)
legend(x="topright",legend=c("观测值","预测值"),lty=1:5,cex=.7)
```

<img src="112_files/figure-html/unnamed-chunk-181-1.png" width="384" />

 分析:由图可以看出三次曲线拟合效果最好


## 11.5下表是2009-2013年我国社会消费品零售总额
### 分别采用Winter指数平滑模型和分解法预测2014年各月份的社会消费品总额，并对实际值和预测值绘图，分析预测效果

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_5.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_5.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## c90b4f03e04d677fa27fb420b7403b3fb9fac5b8
```

```
## [1] "exercise11_5"
```

```r
exercise11_5<-ts(exercise11_5[,3],start=2009,frequency=12)
exercise11_5
```

```
##          Jan     Feb     Mar     Apr     May     Jun     Jul     Aug     Sep
## 2009 10756.6  9323.8  9317.6  9343.2 10028.4  9941.6  9936.5 10115.6 10912.8
## 2010 12718.1 12334.2 11321.7 11510.4 12455.1 12329.9 12252.8 12569.8 13536.5
## 2011 15249.0 13769.1 13588.0 13649.0 14696.8 14565.1 14408.0 14705.0 15865.1
## 2012 17479.9 16188.7 15650.2 15603.1 16714.8 16584.9 16314.9 16658.9 18226.6
## 2013 19629.9 18179.9 17641.2 17600.3 18886.3 18826.7 18513.2 18886.2 20653.3
##          Oct     Nov     Dec
## 2009 11717.6 11717.6 12610.0
## 2010 14284.8 13910.9 15329.5
## 2011 16546.4 16128.9 17739.7
## 2012 18933.8 18476.7 20334.2
## 2013 21491.3 21011.9 23059.7
```

```r
saleforecast<-HoltWinters(exercise11_5)
saleforecast
```

```
## Holt-Winters exponential smoothing with trend and additive seasonal component.
## 
## Call:
## HoltWinters(x = exercise11_5)
## 
## Smoothing parameters:
##  alpha: 0.6362731
##  beta : 0
##  gamma: 1
## 
## Coefficients:
##            [,1]
## a   21375.60330
## b     199.79120
## s1    927.99115
## s2   -267.13392
## s3   -758.13168
## s4   -872.61100
## s5     94.25792
## s6   -290.14470
## s7   -760.21242
## s8   -589.66185
## s9    597.79760
## s10   898.47559
## s11   153.43014
## s12  1684.09670
```

```r
library(forecast)
saleforecast1<-forecast(saleforecast,h=12)
saleforecast1
```

```
##          Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## Jan 2014       22503.39 22011.20 22995.58 21750.65 23256.13
## Feb 2014       21508.05 20924.68 22091.43 20615.86 22400.24
## Mar 2014       21216.85 20554.73 21878.96 20204.23 22229.47
## Apr 2014       21302.16 20569.71 22034.60 20181.98 22422.33
## May 2014       22468.82 21672.23 23265.40 21250.55 23687.09
## Jun 2014       22284.21 21428.27 23140.14 20975.17 23593.24
## Jul 2014       22013.93 21102.51 22925.35 20620.03 23407.83
## Aug 2014       22384.27 21420.55 23348.00 20910.38 23858.16
## Sep 2014       23771.52 22758.19 24784.85 22221.76 25321.28
## Oct 2014       24271.99 23211.37 25332.61 22649.91 25894.07
## Nov 2014       23726.74 22620.85 24832.62 22035.43 25418.05
## Dec 2014       25457.19 24307.82 26606.57 23699.38 27215.01
```

```r
plot(saleforecast1,type='o',xlab="时间",ylab="销售量" ,main="")
```

<img src="112_files/figure-html/unnamed-chunk-182-1.png" width="384" />


 分析：采用Winter指数平滑模型预测2014年各月份的社会消费品总额结果如下：
 Point         Forecast 
 
Jan 2014       22503.39 

Feb 2014       21508.05 

Mar 2014       21216.85 

Apr 2014       21302.16 

May 2014       22468.82 


## 11.6利用习题11.4的数据分别采用m=5和m=10对收盘价格进行平滑，并绘制出实际值与平滑值的图形进行比较

```r
source_data("https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_4.RData?raw=True")
```

```
## Downloading data from: https://github.com/yanliangs/Statistics-with-R/blob/master/exercise/ch11/exercise11_4.RData?raw=True
```

```
## SHA-1 hash of the downloaded data file is:
## cbfa8c42ceb0ccb96dc5c3ca8439b34a2108e429
```

```
## [1] "exercise11_4"
```

```r
head(exercise11_4,10)
```

```
##    时间 盘价格
## 1     1    372
## 2     2    370
## 3     3    374
## 4     4    375
## 5     5    377
## 6     6    377
## 7     7    374
## 8     8    372
## 9     9    373
## 10   10    372
```

```r
exercise11_4=ts(exercise11_4,start=1)
library(DescTools)
m5=MoveAvg(exercise11_4[,2],order=5,align="center",endrule="keep")
m10=MoveAvg(exercise11_4[,2],order=10,align="center",endrule="keep")
data.frame("时间"=exercise11_4[,1],"收盘价格"=exercise11_4[,2],m5,m10)
```

```
##    时间 收盘价格    m5    m10
## 1     1      372 372.0 372.00
## 2     2      370 370.0 370.00
## 3     3      374 373.6 374.00
## 4     4      375 374.6 375.00
## 5     5      377 375.4 377.00
## 6     6      377 375.0 373.45
## 7     7      374 374.6 373.15
## 8     8      372 373.6 372.65
## 9     9      373 372.0 371.80
## 10   10      372 370.6 370.60
## 11   11      369 369.6 369.00
## 12   12      367 368.0 367.30
## 13   13      367 366.2 365.85
## 14   14      365 364.2 364.55
## 15   15      363 362.4 363.15
## 16   16      359 360.8 361.75
## 17   17      358 359.8 360.35
## 18   18      359 358.6 358.65
## 19   19      360 358.0 357.10
## 20   20      357 356.8 356.15
## 21   21      356 354.6 355.65
## 22   22      352 353.2 355.40
## 23   23      348 353.0 355.30
## 24   24      353 353.0 355.30
## 25   25      356 353.8 355.30
## 26   26      356 356.0 355.35
## 27   27      356 357.4 355.55
## 28   28      359 357.6 356.10
## 29   29      360 357.8 357.00
## 30   30      357 357.6 357.95
## 31   31      357 357.0 357.00
## 32   32      355 357.6 355.00
## 33   33      356 359.2 356.00
## 34   34      363 363.0 363.00
## 35   35      365 365.0 365.00
```

```r
par(mai=c(0.7,0.7,0.1,0.1),cex=0.8)
plot(exercise11_4[,2],type='o',xlab="时间",ylab="收盘价格")
lines(m5,type="o",lty=2,col="red")
lines(m10,type="o",lty=6,col="blue")
legend(x="topleft",legend=c("收盘价格","m5","m10"),lty=c(1,2,6),col=c("black","red","blue"),cex=0.8)
```

<img src="112_files/figure-html/unnamed-chunk-184-1.png" width="384" />

 结论：m=10时的拟合度较好
